### ISSUE TITLE
Autoplay and scroll have stopped working

### ISSUE THREAD

**Issue by takeshi-mb** [davidjerleke/embla-carousel#368] opened 2022-09-13 16:03 UTC
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v0.0.0

### Describe the bug

- Basically nothing works because I have 1 or more carousel on a page and they should autoplay, be draggable. It used to work. I didn't change anything since the website is online and now it doesn't work. 

### CodeSandbox

- you can check the website at https://lacasadeinonniboretto.it/

### Steps to reproduce

1. Go to '[homepage](https://lacasadeinonniboretto.it/)' 
2. sections "le nostre camere", "dintorni", "attività" have cards that should autoplay
3. Go to page "[attività](https://lacasadeinonniboretto.it/attivita/)" 
4. sections "i sapori della tradizione", "tutto quello che ti serve" have cards that should autoplay.

### Expected behavior

- it should autoplay and be draggable back and forth

### Additional context

I load the script in the footer with 
<script src="https://unpkg.com/embla-carousel/embla-carousel.umd.js" integrity="sha384-lWKHpTU57iSjoH/TWtwNusIwSYEryNCYtHPVBqdVFI33OmhED0sqW+ezdwLP9c+y" crossorigin="anonymous"></script>
<script src="https://unpkg.com/embla-carousel-autoplay/embla-carousel-autoplay.umd.js" integrity="sha384-Jd95XtQLO46WOjdQlNU/zp5YsXdOk3LDoFOxKeGeYx7oMGOekX6m/oUL4i4/KZ3A" crossorigin="anonymous"></script>

<script type="text/javascript">
	let emblaNodes = document.querySelectorAll(".embla, .embla2");

emblaNodes.forEach(function (emblaNode, i) {
  let options = { loop: false };
  let plugins = [EmblaCarouselAutoplay()] // Plugins

  
  let embla = EmblaCarousel(emblaNode, options, plugins);

 
  
});

</script>

**Comment by davidjerleke** [comment] 2022-09-13 19:03
Hi @takeshi-mb,

If you open up your console in Chrome dev tools you'll see a lot of errors. I'm not sure how you came to the conclusion that these errors are caused by the Embla library but I think you should start lookin elsewhere in order to find the root cause of this. The library script isn't even loaded:

<img width="696" alt="errors" src="https://user-images.githubusercontent.com/11529148/189987616-3ce24fff-6322-4ee5-82f0-0725cb2839b2.png">

Try googling `Failed to find a valid digest in the 'integrity' attribute for resource` and see if you find anything that can help you debug this. Maybe this [StackOverflow question](https://stackoverflow.com/questions/69926878/failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource-in-blazo) will get you on the right track.

Best,
David

**Comment by davidjerleke** [comment] 2022-09-16 12:03
@takeshi-mb did you find the cause?

**Comment by takeshi-mb** [comment] 2022-09-16 13:02
Hi David, thank you for your help. 
Apparently it has to do with the use of SubResource Integrity. Basically my hash do not work anymore and why is yet to be determined. Today I removed them and all is working. I'll try to troubleshoot it and ask somewhere else. Sorry if I thought it was a problem of embla's library. It wasn't loaded because it was blocked by the SRI policy.

**Comment by davidjerleke** [comment] 2022-09-16 18:40
Thanks for the response @takeshi-mb. I'm closing this as resolved then.

Cheers,
David

**Closed by davidjerleke** 2022-09-16 18:40 UTC
Labels: resolved, not a bug
