### ISSUE TITLE
Too many Snaps on Firefox with containScroll: 'trimSnaps'

### ISSUE THREAD

**Issue by mUzzzie** [davidjerleke/embla-carousel#472] opened 2023-05-11 08:38 UTC
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v8.0.0-rc03

### Describe the bug

When having containScroll: 'trimSnaps' enabled and setting slide width relative (e.g. 20%), embla adds empty snaps on Firefox which results in additional navigation dots and enabled arrow buttons when there is nothing to scroll. Sometimes at the beginning, sometimes at the end of the carousel. No issue on Chome or Safari.

### CodeSandbox

https://codesandbox.io/s/mtj878?file=/index.html

### Steps to reproduce

containScroll: 'trimSnaps', slide-width: 20%, 25% + gap, open in Firefox

### Expected behavior

See Chrome

**Comment by davidjerleke** [comment] 2023-05-11 09:02
Hi @mUzzzie,

Thanks for your bug report. This seems to be a bug in Firefox and my initial hunch is that it could be caused by how Firefox handles pixel fractions or similar. As you've mentioned, the Chrome/Safari behaviour is the correct behaviour.

**Chrome/Safari**
<img width="400" alt="chrome:safari" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/d9a02ba1-42e2-4914-b021-ea9f7eb8a5b4">

**Firefox**
<img width="400" alt="firefox" src="https://github.com/davidjerleke/embla-carousel/assets/11529148/2c2bc8fc-99dd-46d9-b84a-48786fcbdfbe">

Feel free to investigate the code and see if you can find the culprit. [This](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/ScrollContain.ts) is the file that is responsible for the `containScroll` logic.

Best,
David

**Comment by mUzzzie** [comment] 2023-05-16 08:38
I'm afraid i'm the wrong person for javascript matters. Sorry I can't help :/
Anyway, are you planning an update regarding this matter? Love the carousel but since in my case everything depends on trimSnaps, i'd have to find another library otherwise. Thanks a lot!

**Comment by mUzzzie** [comment] 2023-05-16 09:15
@davidjerleke Sure, I know - That is why I'm all the more grateful 🙂

**Comment by davidjerleke** [comment] 2023-05-20 18:53
Hi @mUzzzie,

It seems like Firefox is including a lot of decimal places on numbers retrieved from `element.getBoundingClientRect()`. Trimming the decimal places to two or three seems to do the trick (and shouldn't cause any visually noticeable problems).

Please test [this CodeSandbox](https://codesandbox.io/s/embla-carousel-arrow-dots-vanilla-forked-8bmjbf) and see if this is working as expected. It's also good if you test it in Chrome and Safari and try different slide sizes that was causing the problem in Firefox.

Best,
David

**Comment by mUzzzie** [comment] 2023-05-23 06:47
Works perfectly in all browsers!

**Comment by davidjerleke** [comment] 2023-05-23 06:59
Thanks for testing @mUzzzie. To be released with v8.0.0-rc05.

**Closed** 2023-05-24 07:08 UTC
Labels: bug, upcoming

**Comment by davidjerleke** [comment] 2023-05-24 12:04
@mUzzzie this has been released with [v8.0.0-rc05](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc05). Thanks for this bug report.
