### ISSUE TITLE
[Bug]: Extra snapList point on some cases

### ISSUE THREAD

**Issue by huri3l** [davidjerleke/embla-carousel#707] opened 2024-01-21 18:19 UTC
### Version

8.0.0-rc19

### CodeSandbox

[CodeSandbox Link](https://codesandbox.io/p/sandbox/embla-carousel-issue-pnn2cv?file=%2Fsrc%2Fui%2Fcarousel.tsx%3A285%2C27-285%2C37&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrmlgcny00062v6h7whgldg8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrmlgcnx00022v6hggiuvhli%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrmlgcnx00032v6hq91sx5ld%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrmlgcny00052v6h6g9f5j6i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrmlgcnx00022v6hggiuvhli%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrmlgcnx00012v6hyjies7ud%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrn1us8f00022v6hu4qvk8bd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Futils.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrn1v7vf00022v6hnod9kkwh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A285%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A285%252C%2522endColumn%2522%253A37%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fui%252Fcarousel.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrnt9xg800022v6hc53jywd6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Ftailwind.config.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrmlgcnx00022v6hggiuvhli%2522%252C%2522activeTabId%2522%253A%2522clrn1v7vf00022v6hnod9kkwh%2522%257D%252C%2522clrmlgcny00052v6h6g9f5j6i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrmlgcnx00042v6huflso44n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrmlgcny00052v6h6g9f5j6i%2522%252C%2522activeTabId%2522%253A%2522clrmlgcnx00042v6huflso44n%2522%257D%252C%2522clrmlgcnx00032v6hq91sx5ld%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrmlgcnx00032v6hq91sx5ld%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### What browsers are you seeing the problem on?

All of the above

### Steps to reproduce

The bug occurs when I am using the library shadcn/ui, which uses embla-carousel under the hood. In the CodeSandbox, I have used the same code I used and got the issue.

In the example, there is an extra step in the Dots and in the Arrows, which could be eliminated.

https://github.com/davidjerleke/embla-carousel/assets/61247833/85f7f629-e038-4a89-aaa9-7527497365e1

### Expected Behavior

The expected behavior is that it should have only 4 steps, and not 5, since I have 6 content in total and three visible at a time.

### Additional Context

I have debugged a little bit and found out that the problem is not `canScrollNext` or `canScrollPrev`, but actually, when embla identifies how many steps it has.

![image](https://github.com/davidjerleke/embla-carousel/assets/61247833/5f2575d8-da4f-46d5-9582-1cf6772fd827)

As you can see through the image, the snapList goes from 0 to 4, and 3 is a value really close to 1.

Is there anyway to merge this step with the last one?

I am not sure if this is a bug, but if it is not, I haven't found the correct option to use with embla-carousel to fix it. I am already using `containScroll: 'trimSnaps'` and it is still with the undesired behavior.

### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by huri3l** [comment] 2024-01-21 18:28
Also, the goal is to `embla-carousel` detect that the 3rd point is really close to the 4th point (in this example) to merge them into one. I suppose this is happening due to the fact that `flex-basis` is the one who rules how many content will be visible in each slide, and some values of the `flex-basis` are float, leading to this bug.

**Comment by davidjerleke** [comment] 2024-01-21 18:33
@huri3l thanks for your bug report. Before I start investigating this, are you sure that shadcn/ui is using `v8.0.0-rc19`?

It seems like they still have [`v8.0.0-rc15`](https://github.com/shadcn-ui/ui/pull/2286/files#diff-c7ab5a67c7af2cacd4c52613bb9cfe07b9c7a9060819100ca2650aeea79c18b3L58)? Because the pull request I linked to isn’t merged yet.

Best,
David

**Comment by huri3l** [comment] 2024-01-21 18:37
Hi David! Yes, shadcn/ui is using `v8.0.0-rc15`, but in the CodeSandbox I have used the `v8.0.0-rc19` and the bug still occurs.

I have opened this issue here because this behavior is blocking a [pull request](https://github.com/shadcn-ui/ui/pull/2478) where I am implementing dots nagivation.

**Comment by davidjerleke** [comment] 2024-01-21 18:48
@huri3l thanks for confirming. I’ll have a look when possible.

Best,
David

**Comment by davidjerleke** [comment] 2024-01-22 05:02
@huri3l I can confirm that this is a bug. Embla has changed from reading `getBoundingClientRect` to `offsetWidth` and `offsetLeft` recently which has the following benefit:

- #633

With offset dimensions you loose the precision that `getBoundingClientRect` gives you though , and that’s why it requires solutions that has “pixel tolerances” to avoid unexpected behavior. Most of these cases have already been solved like when grouping slides with `slidesToScroll: auto` but I didn’t predict this case.

Thanks for a bug report with good research and I will work on a bug fix as soon as possible.

Best,
David

**Comment by davidjerleke** [comment] 2024-01-22 21:05
@huri3l would you mind testing this [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-issue-forked-rvv8vm?file=%2Fsrc%2Fui%2Fcarousel.tsx%3A2%2C1) to see if you can reproduce the problem?

Another case that triggered this undesired behavior was with 10 slides 20% wide each. If you have a moment, I would appreciate if you could test that too.

Thanks!
David

**Comment by huri3l** [comment] 2024-01-23 12:49
It works wonders @davidjerleke! As far as I have tested, with multiple slides and sizes, there are no problems.

I have also noticed, testing in the current version of the lib, that this problem oftenly occurs when the flex-basis returns a float value. Like the `basis-1/3` class, returns `33.33333...%`.

I tested with other basis that also returned float and the problem was solved in this CodeSandbox too.

Thanks for the fixing man!

**Comment by davidjerleke** [comment] 2024-01-23 13:22
Thanks a lot for taking the time to test the bug fix @huri3l. Much appreciated 👍. I will release `v8.0.0-rc20` as soon as possible which will include this fix.

Best,
David

**Closed** 2024-01-23 14:16 UTC
Labels: bug, core

**Comment by davidjerleke** [comment] 2024-01-23 15:38
@huri3l a bug fix for this was just released in [`v8.0.0-rc20`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc20).

**Comment by huri3l** [comment] 2024-01-23 17:32
Amazing! @davidjerleke will you update the [PR](https://github.com/shadcn-ui/ui/pull/2286/files#diff-c7ab5a67c7af2cacd4c52613bb9cfe07b9c7a9060819100ca2650aeea79c18b3L58) to update `shadcn/ui` package to include this new version?

**Comment by davidjerleke** [comment] 2024-01-23 17:37
@huri3l I’m not the author of that PR, @Xxsource98 is: 

- shadcn-ui/ui#2286
