### ISSUE TITLE
Types from embla-carousel-react not coming through

### ISSUE THREAD

**Issue by Eirfire** [davidjerleke/embla-carousel#679] opened 2024-01-06 01:49 UTC
### Bug is related to

- [ ] embla-carousel (core package)
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation)
- [ ] embla-carousel-docs (generator)

### Embla Carousel version

- v8.0.0-rc18

### Describe the bug
For some reason types from the carousel aren't being exported, this is happening not only locally but also in the sandboxes, I don't know what is up with that. easy fix at my end just install the `embla-carousel` to get the types

### CodeSandbox
https://codesandbox.io/p/sandbox/embla-carousel-generator-react-qx4krj?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A2%2C25

### Steps to reproduce

1. Install the library
2. import types
```ts
import  useEmblaCarousel, {
  type EmblaCarouselType as CarouselApi,
  type EmblaOptionsType as CarouselOptions,
  type EmblaPluginType as CarouselPlugin,
} from "embla-carousel-react";
```
5. See the type errors

### Expected behaviour
Types are exported as they should, this was working only a couple of days ago

**Comment by davidjerleke** [comment] 2024-01-06 04:40
@Eirfire, duplicate of:

- #647

**Closed by davidjerleke** 2024-01-06 04:40 UTC
Labels: bug

**Comment by Eirfire** [comment] 2024-01-06 11:05
Thank you, sorry for the inconvenience I should've checked for existing issues. 

Much appreciated for the such quick response to this.
