### ISSUE TITLE
problem importing types from embla-carousel-react

### ISSUE THREAD

**Issue by 3eisa** [davidjerleke/embla-carousel#665] opened 2023-12-27 17:03 UTC
### Bug is related to

- [ x] embla-carousel (core package)
- [ x] embla-carousel-react

problem importing types from embla-carousel-react

<img width="470" alt="Screenshot 2023-12-27 at 6 56 20 PM" src="https://github.com/davidjerleke/embla-carousel/assets/115343674/b8fe7a73-47da-43db-852b-2c4dff046867">

if we jump to 
node_modules/embla-carousel-react/cjs/index.d.ts
on line 1 : 
export { EmblaOptionsType, EmblaEventType, EmblaPluginType, EmblaCarouselType } from 'embla-carousel/index.ts';
.
cant find 'embla-carousel/index.ts

<img width="1027" alt="Screenshot 2023-12-27 at 6 59 20 PM" src="https://github.com/davidjerleke/embla-carousel/assets/115343674/7d83cd83-2e3b-4b43-901b-286a86db139c">

...
### workaround
<img width="1029" alt="Screenshot 2023-12-27 at 7 00 46 PM" src="https://github.com/davidjerleke/embla-carousel/assets/115343674/663b0c9e-cb1e-4b59-994f-88c7fdc426a8">

by adding "../../"
to point to the 'embla-carousel/index.ts'

changed line 1 to : 
export { EmblaOptionsType, EmblaEventType, EmblaPluginType, EmblaCarouselType } from '../../embla-carousel/index.ts';

**Comment by davidjerleke** [comment] 2023-12-27 17:07
@3eisa see [this](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239). 


- Will be added to the docs here #658.

- Duplicate of #647.

**Closed** 2023-12-27 17:07 UTC
Labels: duplicate
