### ISSUE TITLE
Block excessive scrolling

### ISSUE THREAD

**Issue by jeffsmor** [davidjerleke/embla-carousel#442] opened 2023-03-07 02:08 UTC
Is it possible disable drag to right side when there is no slides to show on left side and vice-versa? 

![untitled](https://user-images.githubusercontent.com/40842204/223301134-2ab03426-529c-4b3d-b58d-149b32b8ea09.png)

tks.

**Comment by davidjerleke** [comment] 2023-03-07 05:21
Hi @jeffsmor,

Thank you for your question. Please create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=q-a) for questions and not a bug report like this.

I think what you want to achieve is covered in [this issue here](https://github.com/davidjerleke/embla-carousel/issues/42#issuecomment-1287131957).

Best,
David

**Comment by davidjerleke** [comment] 2023-03-15 12:26
Hello @jeffsmor,

Let me know if you intend to respond to my comment. If I don’t get any response in 7 days I will delete this issue.

Best,
David

**Comment by jeffsmor** [comment] 2023-03-15 13:18
Hi @davidjerleke 

I achieved what I expected by following this [#42](https://github.com/davidjerleke/embla-carousel/issues/42#issuecomment-895850425)

Thanks.

**Comment by davidjerleke** [comment] 2023-03-15 13:29
Thanks @jeffsmor. Cheers.

**Comment by davidjerleke** [comment] 2023-03-15 14:40
Duplicate of #42

**Closed by davidjerleke** 2023-03-15 14:40 UTC
Labels: duplicate
