### ISSUE TITLE
Timing function

### ISSUE THREAD

**Issue by Filip1139** [davidjerleke/embla-carousel#396] opened 2022-11-14 11:43 UTC
### Feature request is related to

- [x] embla-carousel (core package)

### Is your feature request related to an issue?

I there any way to change timing function of slides transition?

**Comment by davidjerleke** [comment] 2022-11-14 12:04
Hi @Filip1139,

Do you mean applying custom easing? Or just changing speed?

Best,
David

**Comment by davidjerleke** [comment] 2022-11-17 00:18
Duplicate of:

- #184

**Closed by davidjerleke** 2022-11-17 00:18 UTC
Labels: duplicate
