### ISSUE TITLE
[Bug]: beforeUnmount destroys too soon during Vue transitions

### ISSUE THREAD

**Issue by sambedingfield** [davidjerleke/embla-carousel#869] opened 2024-05-12 15:44 UTC
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [X] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

The bug occurs when I transition away a Vue component containing an Embla carousel, causing it to be destroyed too early. This causes a flicker of an unstyled carousel during the transition.

For a common example, imagine a transition on an app route and clicking a link from within a carousel slide.
The user sees the destroyed state of the carousel before the page transitions away.

### Expected Behavior

That either the clean up can be prevented or delayed during `beforeUnmount`.

### Additional Context

To clarify, this [is a known Vue thing](https://github.com/vuejs/vue/issues/6983), and not unique to Embla. It happens with a lot of libraries that clean up using Vue's `beforeUnmount` hook.

A solution could be using a mutation observer or providing a timeout prop to delay the destroying.
Here's how it got discussed for [Splide](https://github.com/Splidejs/vue-splide/pull/81).

This could require a similar solution to the React issue here https://github.com/davidjerleke/embla-carousel/issues/540, where "freezing" styles could work.

I tried the following workaround, but it doesn't consider slides that are translated during loops :
```
beforeUnmount(){
  const x = this.embla.internalEngine().location.get();
  const $cont = this.embla.containerNode();
  $cont.style.transform = 'translateX('+x+'px)';
}
```

### What browsers are you seeing the problem on?

All browsers

### Version

v8.0.4

### CodeSandbox

https://codesandbox.io/p/devbox/reverent-almeida-nh8pkr

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment] 2024-05-13 08:09
@sambedingfield thanks for your bug report. Is this expected behaviour for `onBeforeUnmount`:

- https://github.com/vuejs/vue/issues/6983

Or is it a bug? It seems like some of the comments suggest it's by design? This was the PR where the `onUnmounted` was replaced with `onBeforeUnmount`:

- #673

I'm not a seasoned Vue dev by any means but would re-introducing `onUnmounted` fix the problem? @meirroth and/or @ sadeghbarati, any thoughts on this?

**Comment by sambedingfield** [comment] 2024-05-13 08:35
It doesn't look like it's going to change, so... by design ¯\_(ツ)_/¯
Without any kind of destroy delay or style freeze via Embla there's no other workaround (that I know of) to prevent this.
So feel free to flag this as a feature request instead!

To clarify, both `onUnmounted` and `onBeforeUnmount` trigger beforehand, irrelevant to parent Vue transitions.

**Comment by sadeghbarati** [comment] 2024-05-13 08:36
Will create Vue SFC playground to see differences between Vue versions

IIRC they refactored Transition component alot lately

**Comment by meirroth** [comment] 2024-05-13 08:41
@davidjerleke I'd be concerned about making such a change without extensive testing, especially given any potential errors or performance changes https://github.com/davidjerleke/embla-carousel/issues/672#issuecomment-1872952987.

@sambedingfield Is it possible for you to share a minimal reproduction of the problem you're experiencing so that we can visualize it, debug it, and possibly find a solution? One option I can think of is to use the embla-carousel core without the wrapper and manually destroy it whenever you want. It's actually quite simple, as demonstrated by the [Vue 2 example I provided earlier](https://github.com/meirroth/embla-carousel-vue2/blob/07baf9aaa240063f5ae066e8fca7e3bbd2a02c34/src/components/EmblaCarousel.vue#L33-L38).

**Comment by sadeghbarati** [comment] 2024-05-13 08:42
@meirroth 

Here the [Vue SFC playground](https://play.vuejs.org/#eNqVVdtu2zgQ/ZVZLRbtYquLLTvOatNFd4s+tA9t0RR9qYqAkSibCUUSIuUmMPzvHZKSFTlWL8iLNXNm5syFJ7vgP6WibUuDLLjQRcOUAU1Nq/7NBauVbAzsoKEV7KFqZA15gNg8+OfgfUka2WrKe3cU9xab1SELKbQBTsmWiTU8t+meVoRr+ic6L2JfFevhh6G14sRQ/AK4KNkWCk60fp4HRKk8cGZ0mIYIzQyTAgSpKbqxpMFqHaCL3YasQt9vXekHbgQciMdDUIxRfY14KOLZdM6eWY+7bo1BHi8KzopbrDb0eaLupSE4syFzX8snGdVBAsMw8FObe05BF1LREi0RDgR2NmBD2XpjMpglDa1xont0unGEVBjahKQwbEufHayWFe2sPsPAJwOpSMHMPcyipT6RzG75OJWRPk0XmkHiA3G1ljOSDZ4F/lzCmqjoRkuB5+Zi8s6h8yDzWayN1techEW3odAdUob2jTFKZ3G8JphE1RGTsVB19hj+4jxKokVMdR0/dkZoxvg8wEZO1fuFWpN1flQjbKjfQNgaxl33P9veOHK60zHuQMjyweXscScGr0lUbH20kULWinHavFP2JMabIZzLr2+czTStvSpvLza0uD1hv9F3vrf3DdW02eIiDz58C2tqvPvV5Vt6h78PzlqWLe/WPuH8QLXk2Bw+Iwf7vxUl0n6Ac2xfuwPDd/hRv7ozFC+9a8oSddNweKdsL7/T+kA3jRYPpvhQ76ZV1C2nh35qaa+Xp079oJmfnfcDrb6gnBxneLoDLqXyfcD+V8TUpcoDq8T9FxYZ9PUR9uoKCRnChB3vschWskEcAyZghUmPAjVnJfYEWW9/4izhE/gL2EiSL60ddjtgsMfZntLk/vfPiqTj0KnTljYVnkMGG1aWVOC4AL6y0mysdCZ/dGJ33K4PLpnGKihtFad3Y6TrxqOsE9UP/9LU5nscB3DTasOq+9AWQEnNoHDC6nyEs7UIGbakR/aaibBjaqV1kPxzr/gA16S4XeNliDKD39M07Sj6Sc88uwGDxblsEJmkyVm6GoHnk+C0SFbLceZ0EryaJ4vlcgReTIL/niXkbExjOQmep/MyrUbgs+kGk+X1YjYCr74DPp+tTv3vusLTsaqBrxuffjRfBftvA9gZdw==)

**Comment by sambedingfield** [comment] 2024-05-13 08:47
@meirroth My CodeSandbox is in the original report, here: https://codesandbox.io/p/devbox/reverent-almeida-nh8pkr
And you're correct, a workaround could be to not use the Vue version.

**Comment by meirroth** [comment] 2024-05-13 08:52
@sambedingfield Sorry I missed it 🤦‍♂️ Thanks for sharing.

It seems to me that the issue persists after replacing `onBeforeUnmount` with `onUnmounted` as you can see in this [Vue SFC playground](https://play.vuejs.org/#eNqNVdtu4zYQ/ZWpisIJGl1s2XGqJovdLvLQAr1g074JCBiJsplQJCFS3gSG/71DUrIsrx0s8iLOOTNzOByfbINPSkWblgZZcKuLhikDmppWfcgFq5VsDGyhoRXsoGpkDXmA3Dz4dY9+Jo1sNeU9HMV9xFZ1zEIKbYBTsmFiBXe23EVFuKaXCN7Gviv2w4OhteLEUDwB3JZsAwUnWt/lAVEqD1wYAdMQoZlhUoAgNUUYWxrs1hG63E3IKsR+6FofwEjYC4+HpBiz+h7x0MSr6cBeWc97ao1BHR8LzooX7Dbc80TfB0NwZkPlvpcvMuqDAoZh4FGbN05BF1LREiMRDgS2NmFN2WptMpgmDa1xojsE3ThCKgxtQlIYtqFX+6hVRbuorzDoyUAqUjDzBtNooU8Us698XMpIX6ZLzSDxifi0VjOKDa4Cvy5hTVT0rKXAdXM5eQfoPMh8FRuj9RMnYdG9kIXyYG2M0lkcrwgWUHXEZCxUnY2pH2+iJJrHVNfxGIgwhHl5YFugth1KMjhMUbHVkaBC1opx2vyt7ETGwgjn8usfLmaa1g7Vx4s1LV5OxJ/1q1f/T0M1bTa4onsMV2FFjYfvH/6ir/i9B2tZthzZ74BfqJa8dVvkaL+1okTZBzyn9nc3X1zDf/X9q6H40N2lrFA3Dcd3P+zP71x9kJtG84MpHv7c3zMRKf6ULe5QeYWf/4m6PxyYywRLTPYp9/YBx/YyGT8qcnt3ccAXLOXt5XIU/6TYEM/FXsnFxSXcffBX7InRhvCWIn3U/qKv7+ErvA+XUvkhws4a2a6rvb/a+epRSbVp5JuVY9O+1wNdlTywN+lPKGmwxW+4j484BUOYsGtx7I2VbJDHgAlYYtGjRM1ZifsHWR+fuEg4gZ+BjZz0wcZhuwUGO9yJU1baf3+vtzkNnalsaFPhGmewZmVJBU4a4Csrzdo6XvJT51HH1/XJJdPYBR2p4vR1zHS38SwLomnhX5raet/mATy32rDqLbQN0AkzKJwfOoxwthIhwyvpUbxmIuyUWkccnPrGGzXAEyleVrhhoszgxzRNO4l+0lOvbuBgcy4bZCZpcp0uR+TZWXJaJMvFuHJ6lrycJfPFYkSenyX/Mk3I9VjG4ix5ls7KtBqRr89fMFk8zacj8vId8s10eepfziOujnU7dCW0rGi2DHb/Aw5V/wM=) using embla-carousel core.

**Comment by meirroth** [comment] 2024-05-13 08:59
@davidjerleke Just a thought, do you think this can be fixed by leaving translations as is on destroy?
https://github.com/davidjerleke/embla-carousel/blob/61c050c64b8631f68e091d9e6e1ce96ccad568ad/packages/embla-carousel/src/components/EmblaCarousel.ts#L139C12-L139C21

**Comment by davidjerleke** [comment] 2024-05-13 09:09
@meirroth it can, but not every user would want that. I'm not sure how to solve this in an optimal way. Maybe we can add a parameter to [`destroy()`](https://github.com/davidjerleke/embla-carousel/blob/master/packages/embla-carousel/src/components/EmblaCarousel.ts#L149) like a boolean like so:

```ts
function destroy(keepStyles: boolean): void {
  // ...
}
```

On the other hand, that wouldn't solve this request which is related to this to some extent:

- #540

**Comment by sadeghbarati** [comment] 2024-05-13 09:32
React is working fine with `framer-motion`

https://stackblitz.com/edit/basic-embla-carousel-dthb3k

**Comment by davidjerleke** [comment] 2024-07-30 20:29
@sadeghbarati @sambedingfield @meirroth I'm closing this issue for now if you don't have any objections? My understanding is that this problem has been raised in the `vuejs/core` repository here by @sadeghbarati and it's waiting for a response:

- https://github.com/vuejs/core/issues/10927

**Comment by sambedingfield** [comment] 2024-07-30 21:06
No objections from me. Thanks for raising the problem with Vue!

To conclude from my perspective, I ended up using Embla Core wrapped in a Vue component as suggested. 
I have a prop to control the delay before destroying, so that it can be used with different transition lengths. Works great!

Site launched this week actually! 
https://wondermake.xyz/services/branding <- I use Embla carousels in the hero of each service page, and you can quickly jump between routes using the fixed nav. Buttery smooth!

**Comment by davidjerleke** [comment] 2024-07-31 07:08
@sambedingfield nice work 👍🏻! Feel free to share it here:

- #691

**Comment by meirroth** [comment] 2024-07-31 13:18
@sadeghbarati Stunning website! Bookmarked. Is it plain Vue?

**Comment by sambedingfield** [comment] 2024-07-31 13:34
Thank you! It is. By far, my most favourite stack to work with over the last few years.

![image](https://github.com/user-attachments/assets/89dce66e-a9bb-4863-b8fd-1137d4e0af2f)

**Closed** 2024-07-31 19:20 UTC
Labels: bug, vue

**Comment by davidjerleke** [comment] 2024-08-01 10:19
Anyone who hasn’t done so yet, if you don’t mind, please go to the vuejs/core issue that @sadeghbarati created and give it a thumbs up so it’s clear that it has some traction. That would better out chances of getting it fixed:

- https://github.com/vuejs/core/issues/10927
