### ISSUE TITLE
[Bug]: Video with controls in slide interferes with swiping

### ISSUE THREAD

**Issue by gregg-cbs** [davidjerleke/embla-carousel#891] opened 2024-05-31 05:12 UTC
### Which variants of Embla Carousel are you using?

- [X] embla-carousel-svelte

### Steps to reproduce

Created a carousel with images and video. When arriving on the video slide notice that swiping no longer works, the video seems to absorb the mousedown event and you cannot slide left or right to the next or previous slide.

### Expected Behavior

`<video controls>` elements to allow swiping to the next or previous slide

### Additional Context

![image](https://github.com/davidjerleke/embla-carousel/assets/57114335/83a4c497-7270-49b4-84b3-1d393079d1b7)

### What browsers are you seeing the problem on?

All browsers

### Version

8.0.2

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment] 2024-05-31 07:09
- @gregg-cbs this is a duplicate of https://github.com/davidjerleke/embla-carousel/issues/678#issuecomment-1878210636. Please read the linked comment to see the solution to this.

**Closed** 2024-05-31 07:09 UTC
Labels: duplicate
