### ISSUE TITLE
[Feat]: Add a fade plugin

### ISSUE THREAD

**Issue by dmorda** [davidjerleke/embla-carousel#39] opened 2019-12-23 23:29 UTC
Love the carousel and was able to get it working right away. The one thing that I need that it doesn't provide is a way to have a scroll option for single/multiple slides and a fade option to handle next/previous transition when it's just showing a single slide at a time.

Is that something that has been requested before?

**Comment by davidcetinkaya** [comment] 2019-12-24 07:59
Hi Damon (@dmorda),
Merry Christmas, and thank you for opening this issue 🎅. 

About this:

> A way to have a scroll option for single/multiple slides

Would you mind explaining what you mean a bit more in detail? I need more information in order to answer this question, but I'm going to take a guess and ask if you've checked out the [`slidesToScroll`](https://github.com/davidcetinkaya/embla-carousel#slidestoscroll) option? Here's a [CodeSandbox](https://codesandbox.io/s/embla-carousel-slidestoscroll-1g4rk) that demonstrates how you can achieve this.

The answer to your question about the fade option is no, it has not been requested yet. It's not on the roadmap of Embla but maybe you can achieve this by hooking onto the classname toggling for selected slides? Please have a look at the documentation [here](https://github.com/davidcetinkaya/embla-carousel#selectedclass--type-string).

I hope any of this helps!

Best,
David

**Comment by dmorda** [comment] 2019-12-24 19:08
Thanks for the quick response and a Merry Christmas to you as well. What I'm trying to achieve is a Fade effect , as an example view [this page](https://kenwheeler.github.io/slick/) and search for the word "Fade". That will provide an example of what I'm trying to accomplish.

Let me know if that helps!

**Comment by davidcetinkaya** [comment] 2019-12-25 10:27
Hi again Damon (@dmorda),
Thank you for the clarification, that helps 👍.

The vision for Embla is physics simulated carousels that move in a fluid and natural manner. The assumption here is that the carousel should be scrollable, and this doesn't play well with fade sliders that don't feel natural to drag/swipe. This is why a fade option is not a part of the Embla vision.

But with that said, **I've setup a [CodeSandbox example](https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul) for you**, where I've hacked the fade option by tweaking some CSS.

I hope that you'll find it useful!

Best,
David

**Comment by dmorda** [comment] 2019-12-25 13:22
That small tweak now lets me re-use Embla for both the fade version of a carousel and the normal sliding version. Thanks so much, happy holidays!

**Comment by davidcetinkaya** [comment] 2019-12-25 13:46
Hi Damon (@dmorda),

I’m glad to hear that 🙂. Thank you and happy holidays to you too!

Kindly,
David

**Comment by vntw** [comment] 2021-04-25 19:17
Hey @davidcetinkaya, sorry for digging up an old issue but I found your sandbox for a fade slider (thanks!). While playing around with it, I noticed that every slide is seen as "in view" by the slider and subsequently gets the `selectedClass` **when the window is resized**, meaning no more slides.

I added a `reInit` and `resize` listener to the sandbox [here](https://codesandbox.io/s/embla-carousel-github-issue-39-forked-p3hp0?file=/src/js/index.js:1103-1278) to fix this. If this is the correct change, it might make sense to update your original sandbox for future users that may find this? 

Happy to hear your thoughts on this 🙂 Thanks!

**Comment by davidcetinkaya** [comment] 2021-04-27 07:43
Hi @vntw,

Thank you for noticing this. 

> I added a `reInit` and `resize` listener to the sandbox [here](https://codesandbox.io/s/embla-carousel-github-issue-39-forked-p3hp0?file=/src/js/index.js:1103-1278) to fix this. If this is the correct change, it might make sense to update your original sandbox for future users that may find this?

Your suggestion does the trick, nice work 👍. I've updated the original [CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul). I also added the `skipSnaps: false;` option because skipping slides when vigorous dragging occurs might lead to confusing UX for fade sliders. From the [docs](https://www.embla-carousel.com/api/options/#skipsnaps):

> Allow the carousel to skip scroll snaps if it's dragged vigorously. Note that this option will be ignored if the dragFree option is set to true.

Thank you for your efforts!

Best,
David

**Comment by silllli** [comment] 2021-09-20 18:47
Thank you @davidcetinkaya!

**Comment by davidcetinkaya** [comment] 2021-12-05 13:40
Reopening this:

As of v.6 it’s possible to provide plugins to Embla. A Fade plugin will be added in the future:

- #237

**Comment by aKandzior** [comment] 2022-10-09 08:24
Great solution with the fade effect!

I have an improvement suggestion for the CSS used in the [SandBox](https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul?file=/src/css/embla.css).

I was applying the example CSS code to my project and noticed that since `positon: absolute;` is used to stack the slides, it is also required to set the slide height on the `.embla__container`. 

In my case, I wanted the container to automatically use the height as defined by the slide markup itself. By changing the CSS to use `display: grid;` as per the code below, the height of the slides is still defined by the slide side markup.

```
.embla__container {
  transform: none !important; /* override Embla */
  display: flex;
}

.embla__slide {
  transform: none !important; /* required if loop is active */
  flex: 0 0 auto;
  width: 100%;
  height: 250px;
  opacity: 0;
  transition: opacity 1s;
  counter-increment: embla;
  border-radius: 0.5rem;
  font-size: 5rem;
}

.embla--is-ready .embla__container {
  display: grid;
}

.embla--is-ready .embla__slide {
  grid-row: 1;
  grid-column: 1;
}
```

**Comment by SunpieAgency** [comment] 2023-03-06 07:35
> Great solution with the fade effect!
> 
> I have an improvement suggestion for the CSS used in the [SandBox](https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul?file=/src/css/embla.css).
> 
> I was applying the example CSS code to my project and noticed that since `positon: absolute;` is used to stack the slides, it is also required to set the slide height on the `.embla__container`.
> 
> In my case, I wanted the container to automatically use the height as defined by the slide markup itself. By changing the CSS to use `display: grid;` as per the code below, the height of the slides is still defined by the slide side markup.
> 
> ```
> .embla__container {
>   transform: none !important; /* override Embla */
>   display: flex;
> }
> 
> .embla__slide {
>   transform: none !important; /* required if loop is active */
>   flex: 0 0 auto;
>   width: 100%;
>   height: 250px;
>   opacity: 0;
>   transition: opacity 1s;
>   counter-increment: embla;
>   border-radius: 0.5rem;
>   font-size: 5rem;
> }
> 
> .embla--is-ready .embla__container {
>   display: grid;
> }
> 
> .embla--is-ready .embla__slide {
>   grid-row: 1;
>   grid-column: 1;
> }
> ```

I think best practice would be to set do something like this:

`.embla.fade.ready .embla__slide {
	position: absolute;
}
.embla__slide.is-selected {
	position: relative;
}`

This requires the classes module but works perfect for me. Height of the container is automatically adapted to your selected slide.

**Comment by vettloffah** [comment] 2024-02-26 23:05
The sandbox linked multiple times here doesn't load anymore. Does anyone have a copy of the code?

**Comment by davidjerleke** [comment] 2024-02-27 05:09
@vettloffah please [read this](https://github.com/davidjerleke/embla-carousel/discussions/741#discussioncomment-8415273).

**Comment by davidjerleke** [comment] 2024-03-07 09:53
Finally got an hour without interruptions to work on the `embla-carousel-fade` plugin. I have dragging between slides left to implement. Here's a sneak preview for anyone interested:

https://github.com/davidjerleke/embla-carousel/assets/11529148/8011050e-4c12-45fd-b310-1aa2e9160d95

**Comment by nikolay17538583** [comment] 2024-03-08 09:12
> Finally got an hour without interruptions to work on the `embla-carousel-fade` plugin. I have dragging between slides left to implement. Here's a sneak preview for anyone interested:
> 
>  fade-plugin-wip.mp4

🙏🏼🥺

**Comment by nikolay17538583** [comment] 2024-03-08 19:52
> Finally got an hour without interruptions to work on the `embla-carousel-fade` plugin. I have dragging between slides left to implement. Here's a sneak preview for anyone interested:
> 
> 
> 
> https://github.com/davidjerleke/embla-carousel/assets/11529148/8011050e-4c12-45fd-b310-1aa2e9160d95
> 
> 
> 
> 

David, any info when this will be available? I really need this 🥺

**Comment by davidjerleke** [comment] 2024-03-17 06:55
## Update

We’re getting close to a release people. I only have two edge cases left to fix and after that I will clean up some code and add a page to the documentation.

Anyone who wants to help out and speed up the release of this plugin can keep an eye on this issue as I will publish CodeSandboxes here as soon as I’m done with fixing the edge cases. If you guys test the sandboxes and help out, we might be able to catch some obvious bugs before the release.

Best,
David

**Comment by mil920** [comment] 2024-04-01 09:39
Yes let us know when it's ready i'm interested too :)

**Comment by AndreiMotinga** [comment] 2024-04-03 18:58
@davidjerleke any chance to use this plugin now, even the active dev version?

**Comment by walton-alex** [comment] 2024-04-04 15:35
Same here, I'd be happy to use an active dev version for now too. I appreciate the work @davidjerleke!

**Comment by davidjerleke** [comment] 2024-04-11 07:14
I paused the development on this because I did some bug fixes which were released in [`v8.0.1`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.1) and [`v8.0.2`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.2). But they're released now so I will continue working on the fade plugin. Most things are in place but can't give an ETA of course because I don't have much spare time to begin with.

**Comment by sitoexpress** [comment] 2024-04-16 10:25
@davidjerleke we're using splide in our projects and since it seems it's a dead end, we're thinking to move everything on Embla. A fade plugin would really make it the definitive js carousel!

**Comment by davidjerleke** [comment] 2024-04-25 13:33
> [!IMPORTANT]  
> This is **NOT** the finished product but a **work in progress**. Most things are in place but not everything yet.

### React
- [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-class-names-react-forked-fj6jyk?file=%2Fsrc%2Fjs%2FEmblaCarousel.jsx%3A19%2C21)
- [App view](https://fj6jyk.csb.app/)

**Comment by meirroth** [comment] 2024-04-25 14:02
@davidjerleke Looks perfect! 
Do you think it'll be possible to apply the lazy rendering solution [discussed here](https://github.com/davidjerleke/embla-carousel/discussions/835#discussioncomment-9188550) while using this new plugin? Rendering only the slides in view is especially useful for performance when dealing with heavy content like images (note how in your example app above, all images are loaded even though only one is shown), custom components, or even videos where you want the player to be destroyed when it goes out of view.

**Comment by sarussss** [comment] 2024-04-26 07:14
Hi @davidjerleke.
I think we can modify function positionSlides

```
  function positionSlides() {
    const { scrollSnaps, slideRegistry } = emblaApi.internalEngine()
    const slides = emblaApi.slideNodes()
    scrollSnaps.forEach((scrollSnap, scrollSnapIndex) => {
      const slidesInSnap = slideRegistry[scrollSnapIndex]
      slidesInSnap.forEach((slideIndex) => {
        slides[slideIndex].style.transform = `translateX(${scrollSnap}px)`
      })
    })
  }
```
Replace

```
  function positionSlides() {
    emblaApi.slideNodes().forEach((slide, slideIndex) => {
      slide.style.transform = `translateX(${slideIndex * -100}%)`
    })
  }
```

What do you think, is this possible?
[Demo](https://stackblitz.com/edit/sarusss-autoplay-1qtjye?file=embla-carousel-fade.js,main.js,index.html)

**Comment by sarussss** [comment] 2024-04-26 08:52
@davidjerleke thank you for your feedback. I think it's not really necessary because when using fade, we will adjust the width in the parent element and fade only works well when there is only 1 slide in each viewport.

Don't worry too much about these things, these are just some of my thoughts, because I don't understand Embla as deeply as you do, so if anything is incorrect, please forgive me.

P/S: Thanks for your hard work, the fade plugin is awesome.

[Demo](https://stackblitz.com/edit/sarusss-autoplay-1qtjye?file=main.js)

**Comment by ItsFrankieD** [comment] 2024-05-03 15:18
Out of curiosity, will the fade duration be adjustable? For both autoplay and next / previous trigger, I feel as though a duration adjustment is almost a necessity. Great work thus far!

**Comment by davidjerleke** [comment] 2024-05-03 15:41
@ItsFrankieD yes, the default [duration](https://www.embla-carousel.com/api/options/#duration) option for the carousel constructor changes the fade duration.

**Comment by davidjerleke** [comment] 2024-05-05 20:02
> Do you think it'll be possible to apply the lazy rendering solution [discussed here](https://github.com/davidjerleke/embla-carousel/discussions/835#discussioncomment-9188550) while using this new plugin? Rendering only the slides in view is especially useful for performance when dealing with heavy content like images (note how in your example app above, all images are loaded even though only one is shown), custom components, or even videos where you want the player to be destroyed when it goes out of view. 

@meirroth yes. The plugin will expose the slide opacity states with a method called `opacities()`. Not sure that `opacities` will be the final method name when released though so feel free to suggest a name. Let's say you want to load images for all slides that have an **opacity greater than 0**. You will be able to achieve that like this:

```tsx
function loadImages(emblaApi) {
  const opacities = emblaApi.plugins().fade.opacities();

  opacities.forEach((opacity, snapIndex) => {
    if (opacity === 0) return // Not visible so bail here
    const slidesInSnap = emblaApi.internalEngine().slideRegistry[snapIndex];

    slidesInSnap.forEach((slideIndex) => { /* Load image for slideIndex */ })
  })
} 

emblaApi.on('scroll', loadImages);
```

**Comment by meirroth** [comment] 2024-05-05 21:10
@davidjerleke Thank you! I look forward to using this plugin on our homepage 😃

**Comment by davidjerleke** [comment] 2024-05-07 06:49
@meirroth, @sarussss, @ItsFrankieD,  @sitoexpress, @walton-alex, @AndreiMotinga, @mil920, @HIT2022 and anyone else interested, feel free to test the **fade plugin** [here](https://github.com/davidjerleke/embla-carousel/issues/39#issuecomment-2077198241)?

Let me know how it goes.

**Comment by mil920** [comment] 2024-05-07 06:52
@davidjerleke Thanks i tested it and i adapted it to ts and put it on my shadcn carousel and it work well.

**Comment by davidjerleke** [comment] 2024-05-07 06:58
@mil920 thanks for letting me know! The package is written in TypeScript so that won't be a problem once officially released.

**Comment by meirroth** [comment] 2024-05-07 11:12
> > Do you think it'll be possible to apply the lazy rendering solution [discussed here](https://github.com/davidjerleke/embla-carousel/discussions/835#discussioncomment-9188550) while using this new plugin? Rendering only the slides in view is especially useful for performance when dealing with heavy content like images (note how in your example app above, all images are loaded even though only one is shown), custom components, or even videos where you want the player to be destroyed when it goes out of view.
> 
> @meirroth yes. The plugin will expose the slide opacity states with a method called `opacities()`. Not sure that `opacities` will be the final method name when released though so feel free to suggest a name. Let's say you want to load images for all slides that have an **opacity greater than 0**. You will be able to achieve that like this:
> 
> ```tsx
> function loadImages(emblaApi) {
>   const opacities = emblaApi.plugins().fade.opacities();
> 
>   opacities.forEach((opacity, snapIndex) => {
>     if (opacity === 0) return // Not visible so bail here
>     const slidesInSnap = emblaApi.internalEngine().slideRegistry[snapIndex];
> 
>     slidesInSnap.forEach((slideIndex) => { /* Load image for slideIndex */ })
>   })
> } 
> 
> emblaApi.on('scroll', loadImages);
> ```

@davidjerleke I tested again the Fade plugin you shared, and even [tried it with the Vue wrapper](https://stackblitz.com/edit/embla-carousel-nuxt-fade?file=app.vue) and works perfectly.
Regarding the lazy rendering solution above, would it make sense from API perspective for `slidesInView` to return only the slides that is **currently visible** while using this plugin, as supposed to returning ALL the slides like it does now? I think that will keep the lazy rendering solution consistent between Fade and not Fade carousels.
https://stackblitz.com/edit/embla-carousel-nuxt-fade-lazy?file=app.vue

**Comment by davidjerleke** [comment] 2024-05-10 10:38
> Regarding the lazy rendering solution above, would it make sense from API perspective for slidesInView to return only the slides that is currently visible while using this plugin, as supposed to returning ALL the slides like it does now? I think that will keep the lazy rendering solution consistent between Fade and not Fade carousels.

@meirroth thanks for your ideas! I've updated the work in progress [plugin here](https://github.com/davidjerleke/embla-carousel/issues/39#issuecomment-2077198241) with the following:

### Cleanup function
It's now in place so calling `emblaApi.destroy()` cleans up the inline styles and removes the event listeners that the fade plugin is using.

### Slides in view
I was able to shift slides with `0` opacity out of view using `transform` and it doesn't seem to glitch at all. Try it out if you want and if you agree, this recreates parts of the core Embla functionality which is nice:

```ts
// Logging all slides in view will work
emblaApi.on('slidesInView', (emblaApi) => {
  console.log(emblaApi.slidesInView())
})
```

However, I'm not sure it makes sense to try recreating the [inViewThreshold](https://www.embla-carousel.com/api/options/#inviewthreshold) option. Because when shifting slides with `0` opacity out of view and `> 0` in view they will disappear/appear entirely in contrast to a scrolling carousel where the slides gradually scroll into view.

**Comment by meirroth** [comment] 2024-05-10 15:23
> However, I'm not sure it makes sense to try recreating the [inViewThreshold](https://www.embla-carousel.com/api/options/#inviewthreshold) option. Because when shifting slides with `0` opacity out of view and `> 0` in view they will disappear/appear entirely in contrast to a scrolling carousel where slides gradually scroll into view.


@davidjerleke Not sure I follow 😬 But my lazy load implementation above works with your update, and 100% matches non fade carousels which is neat!

**Comment by sarussss** [comment] 2024-05-11 01:01
Hi @davidjerleke 
Effect fade only work on desktop.
Mobile will run as a slide effect as usual.
Is there any way to achieve that?

**Comment by davidjerleke** [comment] 2024-05-11 04:17
@sarussss I don’t have this problem. Are you sure you’ve checked everything in your code?

@meirroth how about you?

**Comment by sarussss** [comment] 2024-05-11 04:29
Hi @davidjerleke.
I mean I want to do that:
- Desktop: Use fade effect.
- Mobile: Use effect slide.

It's not a bug, I want to do it with embla, but I don't know how to do it.

**Comment by davidjerleke** [comment] 2024-05-11 06:01
@sarussss use the breakpoints option:

```ts
const emblaNode = document.querySelector('.embla')
const emblaApi = EmblaCarousel(emblaNode, { loop: true }, [Fade({
  breakpoints: {
    '(min-width: 768px)': { active: false }
  }
})])
```

**Comment by sarussss** [comment] 2024-05-11 06:21
@davidjerleke thank of ton.

**Comment by davidjerleke** [comment] 2024-05-11 06:24
@sarussss don’t forget to grab the latest updates from the work in progress React [sandbox](https://codesandbox.io/p/sandbox/embla-carousel-fade-work-in-progress-fj6jyk). Just copy the plugin code from the sandbox and replace it with your current plugin code.

**Comment by davidjerleke** [comment] 2024-05-12 06:28
One last thing to solve before creating the Fade plugin documentation page and publishing it:

The `emblaApi.scrollProgress()` doesn’t work with fade right now. The logic has to change because there is no concept of distance that can differ between two slides anymore. It’s now a matter of the target slide fading from 0 to 1 opacity. It also has to work with loop activated.

**Comment by davidjerleke** [comment] 2024-05-12 14:54
Only code cleanup and creating the documentation page for the fade plugin left to do before release. All features done ✅.

**Closed** 2024-05-16 08:06 UTC
Labels: feature request, upcoming, plugin

**Comment by silllli** [comment] 2024-05-16 09:49
Awesome, thank you!

**Comment by davidjerleke** [comment] 2024-05-17 09:58
Released in [`8.1.0`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.0)

**Comment by ribeiroeder** [comment] 2024-06-16 05:43
Just for those who can help, in my tests the fade effect seemed a little stuck, perhaps due to the greater number of children in the item, In JS I used duration with 20 and in CSS this rule made it smoother;

```
.embla__slide {
    transition-timing-function: linear;
}
```

**Comment by meirroth** [comment] 2024-06-16 19:57
@ribeiroeder I suggest you also try lazy loading slides, that might help performance. Here's the implementation from earlier in this thread: https://stackblitz.com/edit/embla-carousel-nuxt-fade-lazy?file=app.vue
