### ISSUE TITLE
[Bug]: any type for `Autoplay` plugin options

### ISSUE THREAD

**Issue by musjj** [davidjerleke/embla-carousel#887] opened 2024-05-27 19:28 UTC
### Which variants of Embla Carousel are you using?

- [ ] embla-carousel **(Core)**
- [ ] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [X] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

```typescript
import Autoplay from "embla-carousel-autoplay";

Autoplay({|})
```

When hovered:

```typescript
(alias) Autoplay(userOptions?: any): CreatePluginType<{
                               ^^^
    play: (jump?: boolean | undefined) => void;
    stop: () => void;
    reset: () => void;
    isPlaying: () => boolean;
}, CreateOptionsType<{
...
```

The typescript definition itself seems fine:

```typescript
declare function Autoplay(userOptions?: AutoplayOptionsType): AutoplayType;
```

Weirdly the completion works in codesandbox, but not in my local VS Code environment.

### Expected Behavior

Types should not be `any`.

### Additional Context

Not sure of any ways of fixing it. But it does look suspiciously similar to this years-old resolved bug: https://github.com/microsoft/TypeScript/issues/7485

### What browsers are you seeing the problem on?

All browsers

### Version

v8.1.3

### CodeSandbox

https://codesandbox.io/p/github/musjj/embla-any-repro

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment] 2024-06-07 10:30
@musjj please create a temporary repository and add instructions on how to reproduce this problem. The Stackblitz you shared isn't enough for me to reproduce it.

Let me know if you intend to provide a repository and steps to reproduce the problem.

**Comment by davidjerleke** [comment] 2024-06-07 11:00
@musjj you don't have a `tsconfig.json` so I guess TypeScript doesn't know how to resolve it. Adding this solves the problem:

`tsconfig.json`

```tsx
{
  "compilerOptions": {
    "moduleResolution": "node"
  },
  "include": ["index.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by musjj** [comment] 2024-06-07 12:22
In most React-based projects, you would set `moduleResolution` to `Bundler`. With this config:

```json{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Bundler"
  },
  "include": ["index.ts"],
  "exclude": ["node_modules"]
}
```

The completion fails.

**Comment by davidjerleke** [comment] 2024-06-07 16:18
> In most React-based projects, you would set `moduleResolution` to `Bundler`. 

@musjj I don’t know how widely the bundler setting is used but just claiming that without proof isn’t convincing.

Anyway, regardless if that’s true or not, Embla was around before the `bundler` setting was introduced so this is not a bug but a feature request. And I don’t really see the point of a duplicate issue because this is already tracked here:

- #778 

But maybe you didn’t know that this was related to that. Closing as a duplicate.

**Closed by davidjerleke** 2024-06-07 16:18 UTC
Labels: bug, awaiting response

**Comment by AntoLepejian** [comment] 2024-06-12 11:00
Hi @davidjerleke !

Thanks for actioning this! While this did resolve the issue, there appears to be some type incompatibility between the main package, and this plugin's one (maybe others too, haven't checked).

**Comment by davidjerleke** [comment] 2024-06-12 11:18
@AntoLepejian does this happen if you pass the plugin directly too like below?

```tsx
const [carouselRef, controller] = useEmblaCarousel(
  { ...opts },
  [Autoplay({
    playOnInit: false,
    delay: AUTOPLAY_DELAY_MS,
  })],
);
```

If not, I've found some errors that I have actioned in this PR:

- #912

**Comment by AntoLepejian** [comment] 2024-06-12 11:28
@davidjerleke yeah happens regardless.

Here's my workaround

```ts
type UseCarouselParameters = Parameters<typeof useEmblaCarousel>;
type CarouselPlugin = UseCarouselParameters[1];

Autoplay({
          playOnInit: false,
          delay: AUTOPLAY_DELAY_MS,
        }) as unknown as NonUndefined<CarouselPlugin>[0]
```

**Comment by davidjerleke** [comment] 2024-06-12 11:31
@AntoLepejian thanks. Let's see if this PR will resolve the issue then:

- #912

**Comment by davidjerleke** [comment] 2024-06-12 12:37
@AntoLepejian feel free to try [v8.1.5](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.5) out now and see if it solves the problem.

**Comment by AntoLepejian** [comment] 2024-06-12 12:44
> @AntoLepejian feel free to try [v8.1.5](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.5) out and see if it solves the problem.

@davidjerleke solved both issues 🚀 🚀

**Comment by AntoLepejian** [comment] 2024-06-12 12:53
There is an another issue where the plugin doesn't seem to have state isolation, and when `autoplay.play` is called, all carousels with the plugin are playing.

I can work around this by adding a unique `id` as a `key` to each carousel, but I think there's a problem on the plugin/carousel side. I'll raise a new issue once I dig into this a bit more

**Comment by davidjerleke** [comment] 2024-06-12 13:03
@AntoLepejian thanks for testing 👍!
