### ISSUE TITLE
Custom Transition in Embla Carousel Slider

### ISSUE THREAD

**Issue by rkgain** [davidjerleke/embla-carousel#314] opened 2022-05-16 19:51 UTC
We cannot set custom transitions or delay in each transition while slide (e,g The slider used in this [site](https://www.jannataresort.com/en/homepage) has a nice transition effect). We have speed to control the overall transition but not transition type. Please if that can be added it will be a super cool slider. At least some basic transition can be added if possible like

    **ease** - specifies a transition effect with a slow start, then fast, then end slowly (this is default)
    **linear** - specifies a transition effect with the same speed from start to end
    **ease-in** - specifies a transition effect with a slow start
    **ease-out** - specifies a transition effect with a slow end
    **ease-in-out** - specifies a transition effect with a slow start and end
    **cubic-bezier(n,n,n,n)** - lets you define your own values in a cubic-bezier function

Or if someone know how we can achieve the same please feel free to assist. :-)

**Comment by davidjerleke** [comment] 2022-05-18 08:15
Hi @rkgain,

Hope you're doing good! Maybe you did search existing issues before creating this issue. But if you didn't, a friendly reminder: Please take a moment to browse issues before you create a new one. This has been brought up before:

- #184

Best,
David

**Comment by davidjerleke** [comment] 2022-05-18 08:16
Duplicate of:
- #184.

**Closed by davidjerleke** 2022-05-18 08:16 UTC
Labels: feature request
