### ISSUE TITLE
[Feat]: Add TypeScript moduleResolution: bundler support

### ISSUE THREAD

**Issue by crashton28** [davidjerleke/embla-carousel#778] opened 2024-02-29 15:05 UTC
### Which variants of Embla Carousel are you using?

- [x] embla-carousel **(Core)**
- [x] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [x] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

In attempting to use the `isPlaying` method as well as the `autoplay:stop` and `autoplay:play` event listeners the types are not found.  This project is currently within a monorepo and using `pnpm`.

We are able to resolve the issue by updating our `tsconfig` with the following, however we are not able to make this change as we need `moduleResolution` to be set to `bundler` for our builds.

```
"moduleResolution": "node10",
"module": "ESNext"
```

Screenshots of the errors within VSCode

![Screenshot 2024-02-29 at 9 58 20 AM](https://github.com/davidjerleke/embla-carousel/assets/15710355/b8cab703-330d-426e-96e3-f5c731a804d8)

![Screenshot 2024-02-29 at 9 58 39 AM](https://github.com/davidjerleke/embla-carousel/assets/15710355/413620b1-96f6-4c3e-9906-e347cadcea6b)

![Screenshot 2024-02-29 at 9 58 48 AM](https://github.com/davidjerleke/embla-carousel/assets/15710355/d7577f25-33c4-4172-ae71-e06e3204110b)

### Expected Behavior

Types would have been found

### Additional Context

I have also tried...

### Version

v8.0.0

### CodeSandbox

[CodeSandbox: Monorepo with TS Error](https://codesandbox.io/p/devbox/embla-carousel-autoplay-react-forked-7tkpmg?file=%2Fpackages%2Fui%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A62%2C48)

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment] 2024-02-29 15:17
@crashton28 thanks for your bug report. Please create a minimal reproduction environment as it’s mandatory if you want me to look into this.

Best,
David

**Comment by crashton28** [comment] 2024-02-29 18:45
[CodeSandbox: Monorepo with TS Error](https://codesandbox.io/p/devbox/embla-carousel-autoplay-react-forked-7tkpmg?file=%2Fpackages%2Fui%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A62%2C48)

**Comment by crashton28** [comment] 2024-02-29 18:46
I've added a codesandbox demo to the original issue above

**Comment by davidjerleke** [comment] 2024-03-01 08:41
@crashton28 thanks. Unfortunately I can't access files under `node_modules` to debug this. I think we need a "real" repository and not a CodeSandbox in this case.

As you mention, setting `moduleResolution: node` solves it so this is related to:

- https://github.com/davidjerleke/embla-carousel/discussions/726#discussioncomment-8331396

But I don't know **why** yet. Feel free to help me out and read about the new `bundler` option that TypeScript have causes these errors. It feels like devs spend 90% of their time with bundlers and problems related to them so I'm happy that we finally we have yet another option that can cause bundling problems. Yaay 😉! 

Best,
David

**Comment by paulmolluzzo** [comment] 2024-03-04 15:26
@davidjerleke The node_modules for a `pnpm` project are in the `.pnpm` folder. I can access the node modules for the Embla packages accordingly (tried in an incognito window to be sure I didn't have some special perms).

Direct link to the autoplay declaractions for example: https://codesandbox.io/p/devbox/embla-carousel-autoplay-react-forked-7tkpmg?file=%2Fnode_modules%2F.pnpm%2Fembla-carousel-autoplay%408.0.0_embla-carousel%408.0.0%2Fnode_modules%2Fembla-carousel-autoplay%2Fesm%2Fcomponents%2FAutoplay.d.ts

![Screenshot 2024-03-04 at 10 25 13 AM](https://github.com/davidjerleke/embla-carousel/assets/737065/cf2361d1-453a-43bc-b270-72c8951077fd)

**Comment by crashton28** [comment] 2024-03-04 15:26
The codesandbox is a dev box so you should be able to download and install the node modules for debugging.  
![image](https://github.com/davidjerleke/embla-carousel/assets/15710355/c090cf91-e141-4ede-8165-30b6f76f306b)

**Comment by davidjerleke** [comment] 2024-03-04 15:32
@paulmolluzzo do you mean that you can access the types without any problems?

**Comment by davidjerleke** [comment] 2024-03-04 15:38
@crashton28 thanks. I will look into it when possible. Meanwhile: Feel free to help out.

Best,
David

**Comment by paulmolluzzo** [comment] 2024-03-04 15:56
> @paulmolluzzo do you mean that you can access the types without any problems?

No, I mean anyone can access the node_modules of a codesandox on that website. The screenshot shows you where it is and the link brings you there directly. 😄

**Comment by davidjerleke** [comment] 2024-03-04 16:06
@paulmolluzzo yes thanks. Didn’t know that so debugging will be easier know that you made me aware of that 🙂.

**Comment by davidjerleke** [comment] 2024-03-31 11:21
Changing label to feature request because `moduleResolution: bundler` was released with TypeScript 5.0 16 March 2023 when Embla already existed.

**Comment by davidjerleke** [comment] 2024-04-11 07:22
Anyone who wants to contribute can look into this issue, because it doesn't require any prior knowledge of how Embla works. I'm busy building the fade plugin so it would really help.

Best,
David

**Comment by fethca** [comment] 2024-05-13 14:13
> @crashton28 thanks. Unfortunately I can't access files under `node_modules` to debug this. I think we need a "real" repository and not a CodeSandbox in this case.
> 
> As you mention, setting `moduleResolution: node` solves it so this is related to:
> 
> * [[Help]: Cannot find module 'embla-carousel/components/Options' or its corresponding type declarations. #726 (reply in thread)](https://github.com/davidjerleke/embla-carousel/discussions/726#discussioncomment-8331396)
> 
> But I don't know **why** yet. Feel free to help me out and read about the new [`bundler`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler) option that TypeScript introduced recently which is causing these errors.
> 
> It feels like devs spend 90% of their time with bundlers and problems related to them so I'm happy that we finally we have yet another option that can cause bundling problems. Yaay 😉!
> 
> Best, David

Hi David,

I made a PoC on embla-carousel-react and its dependencies on this [fork](https://github.com/fethca/embla-carousel). I've integrated [this version](https://www.npmjs.com/package/@fethcat/embla-carousel-react) into one of my React applications for testing. My commits are a bit messy cause I struggled with rollup and versionning. I disabled the docs to focus only on the modules I needed and I didn't adapt the tests. I think it'll be a good oppotunity to use vitest (that's why I switched to nodenext on my repos). Basically the main change is specifying the files extension so that Typescript knows if it's a cjs file or not, [here for example](https://github.com/fethca/embla-carousel/blob/master/packages/embla-carousel/src/components/Animations.ts), . I might do a complete PR if I have the time.  

Best, 
Jay

**Comment by davidjerleke** [comment] 2024-06-08 06:30
Hi @fethca,

Thanks for your efforts. It rather seems like the problem is related to import paths accessing types from package sub folders. With the `bundler` setting active, TypeScript seems to not like that and only accepts type imports from the package root. You can see the changes done in my PR here:

- #901

**Comment by davidjerleke** [comment] 2024-06-10 09:47
@fethca my guess would be that you changed this:

```diff
{
-  moduleResolution: "bundler"
+  moduleResolution: "node"
}
```

But when testing my changes in the PR locally, I can make it work with `moduleResolution: "bundler"` too.

**Comment by fethca** [comment] 2024-06-10 10:02
@davidjerleke  my applications are on `nodenext`, so moduleResolution is also `nodenext`. I remember switching to tauri after I faced the issue and I let their default tsconfig parameters. It turns out it's `"skipLibCheck": true` that solved my problem, which makes sense cause Typescript will igore errors from embla package. I'll try the new version when you'll merge it and let you know if it fixes it. For more context here's my current tsconfig.json file : 

```
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "nodenext",
    "target": "ESNext",
    "strict": true,
    "resolveJsonModule": true,
    "jsx": "react-jsx",

    /* Tauri base parameters */
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "composite": true,
    "allowSyntheticDefaultImports": true,

    /* Linting */
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  }
}
```

**Closed** 2024-06-11 11:09 UTC
Labels: feature request, upcoming, typescript

**Comment by davidjerleke** [comment] 2024-06-11 11:31
@paulmolluzzo, @crashton28, @fethca and anyone else having problems with the `moduleResolution: 'bundler'` setting. Try [`v8.1.4`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.4) that includes a fix for this and let me know how it goes.

**Comment by fethca** [comment] 2024-06-11 14:39
@davidjerleke no change for me on nodenext. Here's a screenshot  : 
![image](https://github.com/davidjerleke/embla-carousel/assets/31514619/1faa3ffd-5819-4c37-9891-4b1325e9821e)

The import paths in the esm folders as I did in the PoC above will be compulsory for `moduleResolution:'nodenext'`. I could open a separate issue if this version fixes it for the other `moduleResolution` settings

**Comment by davidjerleke** [comment] 2024-06-11 14:53
@fethca I see. But this issue is about `moduleResolution: 'bundler'` so I think that should be separate from this issue.

**Comment by fethca** [comment] 2024-06-11 15:00
Yep I agree, I came here cause I looked for `Cannot find module 'embla-carousel/components/Options'`, my first comment wasn't that clear. I'll open a new issue
