### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by mehdiraized** [davidjerleke/embla-carousel#680] opened 2024-01-06 11:38 UTC
### Bug is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react

### Embla Carousel version

- v8.0.0-rc18

### Describe the bug
```
Type error: '"embla-carousel-react"' has no exported member named 'EmblaCarouselType'. Did you mean 'UseEmblaCarouselType'?

> 1 | import { EmblaCarouselType } from 'embla-carousel-react';
```

### Steps to reproduce

1. run 'npm run build'
2. See error

**Comment by davidjerleke** [comment] 2024-01-06 12:08
@mehdiraized a friendly reminder: If you didn’t, please search for existing issues before creating a new issue. 

Duplicate of:

- #647

**Closed by davidjerleke** 2024-01-06 12:08 UTC
Labels: bug
