### ISSUE TITLE
Automatic and slow scroll with dragFree

### ISSUE THREAD

**Issue by flayks** [davidjerleke/embla-carousel#105] opened 2020-09-18 10:14 UTC
I was wondering if there is a way to slowly auto scroll the content of a carousel with the `dragFree` option? In order to sort of show to users that there is more content in a nice way.

Kind of something like that, but automatically:

![autoscroll](https://user-images.githubusercontent.com/273716/93586286-5e4abe00-f9a8-11ea-936b-6b09393e631a.gif)

**Comment by davidcetinkaya** [comment] 2020-09-20 10:17
Hello Félix,

How about this [CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-105-i2gji?file=/src/js/EmblaCarousel.js)? Does it meet your requirements?

Best,
David

**Comment by flayks** [comment] 2020-09-20 10:23
@davidcetinkaya, you are a code angel! It absolutely does what I had in mind. Thank you 🙌

**Comment by davidcetinkaya** [comment] 2020-09-20 10:25
Great news @flayks! I'm closing this as resolved then. Enjoy 🙂.

**Closed by davidcetinkaya** 2020-09-20 10:25 UTC
Labels: duplicate

**Comment by flayks** [comment] 2020-09-21 11:00
Alright @davidcetinkaya, I spoke too soon.

I'm facing some issues with this feature, I'm using Next. Related to the code you made as well for the breakpoint checking, this throws me back a 500 error. Not much detail tho, unfortunately :/
If you have any idea? Have I dont something wrong in my component logic or code?

```react
import React, { useState, useEffect, useCallback } from 'react'
import { useEmblaCarousel } from 'embla-carousel/react'
import { debounce } from '../../utils/functions'


const Scroller = ({ children, screenThreshold = 549, settingsProps = {} }) => {
    const [isActive, setIsActive] = useState(false)
    const [scrollProgress, setScrollProgress] = useState(0)
    const [scroller, embla] = useEmblaCarousel({
        // Settings
        containScroll: 'trimSnaps',
        dragFree: true,
        ...settingsProps
    })


    // Check
    const checkEmbla = useCallback(() => {
        // Enable only on a small screen
        const smallScreen = document.documentElement.clientWidth < screenThreshold
        setIsActive(smallScreen)

        if (isActive) {
            // Scroll event
            onScroll()
            embla.on('scroll', onScroll)

            // Auto scroll slowly
            const engine = embla.dangerouslyGetEngine()
            engine.scrollBody.useSpeed(0.01)
            engine.scrollTo.index(embla.scrollSnapList().length - 1)
        }
    }, [embla, setIsActive])


    // On scroll
    const onScroll = useCallback(() => {
        if (!embla) return

        // Update scrollbar when scrolling
        setScrollProgress(Math.max(0, Math.min(1, embla.scrollProgress())) * 100)
    }, [embla, setScrollProgress])


    // Init
    useEffect(() => {
        // Check for carousel
        checkEmbla()

        // Resize
        window.addEventListener('resize', debounce(checkEmbla, 150))
    }, [checkEmbla])


    return isActive ? (
        <div className="scroller">
            <div className="scroller__container grid" ref={isActive ? scroller : null}>
                <div className="scroller__pan">
                    {children.map((child, index) => (
                        <div className="scroller__item" key={index}>
                            {child}
                        </div>
                    ))}
                </div>
            </div>

            <div className="scroller__progress">
                <div style={{ transform: `translateX(${scrollProgress}%)` }} />
            </div>
        </div>
    ) : children
}

export default Scroller
```

**Comment by flayks** [comment] 2020-09-21 11:06
I suspect that the problem is coming from this line:

```jsx
engine.scrollBody.useSpeed(0.01)
```

Commenting it indeed takes the Scroller component to the last item with no dramas, but as soon as I set the `scrollBody.useSpeed` method, I get the error. Mysterious 🤔

**Comment by davidcetinkaya** [comment] 2020-09-21 11:17
Hi @flayks,

Just guessing but maybe you should perform a check if the window object exists? It won’t be there on the server right?

Best,
David

**Comment by flayks** [comment] 2020-09-21 11:18
@davidcetinkaya that is true. Does `engine.scrollBody.useSpeed()` uses `window` or `document`?

**Comment by davidcetinkaya** [comment] 2020-09-21 11:20
Not sure because I don’t have access to my computer right now. Try document?

**Comment by davidcetinkaya** [comment] 2020-09-21 11:28
I noticed that your checkEmbla function doesn’t check for the existence of the `embla` variable before executing the scrolling?

**Comment by flayks** [comment] 2020-09-21 11:34
@davidcetinkaya I'll give it a try.

I tried to add it at the first place, but as soon as I do that:

```jsx
const checkEmbla = useCallback(() => {
        if (!embla) return
...
```

It stops any kind of code after and breaks the detection with the breakpoint.

**Comment by davidcetinkaya** [comment] 2020-09-21 11:37
@flayks the if statement should probably be inside isActive and wrap the auto scrolling code.

**Comment by flayks** [comment] 2020-09-21 11:48
@davidcetinkaya right. It works in the isActive indeed, thanks!  
Although, no luck for checking for `window` or `document` for `engine.scrollBody.useSpeed()`.

**Comment by davidcetinkaya** [comment] 2020-09-21 11:51
Maybe the window you use for the resize handler and the document for clientWidth need checks so they don’t cause 500 on the server side (unrelated to Embla)?

**Comment by flayks** [comment] 2020-09-21 12:23
@davidcetinkaya I think it's alright as the whole code is ran in an `useEffect` method which is not rendered by Next. It runs pretty smoothly except for the `useSpeed` function

**Comment by davidcetinkaya** [comment] 2020-09-21 12:32
@flayks I see. Is the issue present on the browser or server?

**Comment by flayks** [comment] 2020-09-21 15:56
@davidcetinkaya ok, I've done some investigating and with a fresh NextJS app and only the Scroller component with some divs in it, it works. It must be from somewhere else in my app? Can't say where but I'll have a deeper look. The code works tho!

**Comment by flayks** [comment] 2020-09-21 20:27
Okay @davidcetinkaya, I've got some news, and it's (I suppose), not Embla, but Preact. I configured my NextJS project using Preact instead of React, and there is something in the `useSpeed` that it doesn't like. What exactly is the question because even with the debugger/profiler I have close to 0 log, but that's the reason behind this confusion!

**Comment by davidcetinkaya** [comment] 2020-09-22 05:11
Thanks for the update @flayks. So do you intend to use Embla with React or Preact? Or was the Preact setup a mistake?

Sounds strange, but I only have experience with React, not Preact, so I can’t even start guessing why this is happening. Especially without an error log.

**Comment by flayks** [comment] 2020-09-22 09:12
@davidcetinkaya I started the project using Next with React but I tried to use Preact in order to reduce the bundle size, but I feel that it's causing more issues than giving a lightweight code haha
I created a repo replicating my setup: https://github.com/flayks/embla-next-preact
As I mentioned, hardly any errors or logging, it only works without the line 35 of the `Scroller.jsx` file.
Not a huge deal IMO, but that's a bit odd.

**Comment by davidcetinkaya** [comment] 2020-09-22 09:29
Thanks for clarifying Félix (@flayks). That sounds a bit odd yeah. With no intention to be rude, at the time of writing Embla Carousel works with Vanilla-JS and React. I haven't tested Preact at all. I might decide to add support in the future and in that case the repo you shared may be helpful for debugging purposes 👍.

I'm glad it works with React though 🙂.

Best,
David

**Comment by flayks** [comment] 2020-09-22 09:32
@davidcetinkaya no worries. I just found that weird. As I don't know much about Preact either I just wanted to give it a go, but no big deal really, I switched back to React instead. That would be good for the peeps using it tho, as it's a super good lightweight alternative to React. Thanks for your help anyway!

**Comment by ameliagroen** [comment] 2022-06-15 10:06
How to make this work with current version of Embla and Vanilla JS? I've tried this

```
const engine = embla.internalEngine;
engine.scrollBody.speed( 0.05 );
engine.scrollTo.index(embla.scrollSnapList().length - 1);
```
But the slider moves in the opposite direction of the codesandbox example. The velocity effect is seemingly also still turned on because it starts at the speed I set and then slows down.

**Comment by NickWoodward** [comment] 2023-09-08 19:05
just stumbled across this and wondered if this is an alright approach to the same problem?

```
  const autoplayOptions = {  delay:0,  rootNode: (emblaRoot: HTMLElement) => emblaRoot.parentElement}
  const options = { loop: true, duration: 8000 }
  
  const [emblaRef, emblaApi] = useEmblaCarousel(options, [Autoplay(autoplayOptions)])

```

**Comment by raymondarevalo** [comment] 2024-01-25 19:46
@davidjerleke Would your solution work in vanilla JS?

**Comment by davidjerleke** [comment] 2024-01-25 20:47
- Duplicate of #114.

@raymondarevalo no need to look for temporary CodeSandbox solutions anymore. A plugin for this is finished and will be [released very soon](https://github.com/davidjerleke/embla-carousel/issues/114#issuecomment-1895423531). Stay tuned.

Here’s the PR for it:

- #634

**Comment by alisayed95** [comment] 2024-02-09 11:22
> CodeSandbox

the link is not working.

**Comment by davidjerleke** [comment] 2024-02-09 11:30
@alisayed95 no example sandbox yet but the plugin [has been released](https://www.embla-carousel.com/plugins/auto-scroll/).

**Comment by raymondarevalo** [comment] 2024-02-19 04:44
@davidjerleke random question, but would you have any reference on how 'embla.dangerouslyGetEngine()' was used before this new plugin? 

I'm currently doing this
```
    const engine = this.carousel.internalEngine();
    engine.location.add(this.speed);
    engine.target.set(engine.location);
    engine.scrollLooper.loop(this.speed);
    engine.slideLooper.loop();
    engine.translate.to(engine.location);
```

But then realized I should probably be using 'dangerouslyGetEngine()'

**Comment by davidjerleke** [comment] 2024-02-19 09:54
@raymondarevalo what do you want to achieve? If it's unrelated this issue. Please [ask for help](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) here.

**Comment by raymondarevalo** [comment] 2024-02-19 15:43
@davidjerleke  Oh yeah, it's related to this issue. Basically I wanted to create an infinite loop using a previous method that was being used on this thread. However, I noticed that the engine.location wasn't being reset after an entire loop and therefore embla.scrollProgress() was going beyond 1. 

`
loop() {
    if (this.paused) return;
    const engine = this.carousel.internalEngine();

    engine.location.add(this.speed);

    engine.target.set(engine.location);

    engine.scrollLooper.loop(this.speed);
    engine.slideLooper.loop();
    engine.translate.to(engine.location);

    console.log("slide scroll progress", this.carousel.scrollProgress());

    const that = this;
    this.raf = window.requestAnimationFrame(() => that.loop());
  }
`

I'm currently using 'embla 7.1'.

Last note, I tried using the new plugin, but realized it broke whenever I resized the screen.
