### ISSUE TITLE
Library crash when using breakpoints

### ISSUE THREAD

**Issue by hamidrezahanafi** [davidjerleke/embla-carousel#519] opened 2023-07-07 15:32 UTC
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v8.0.0-rc07

### Describe the bug

- When using breakpoints, if there are not enough slides to cover the whole screen, the library crashes
`RangeError
Maximum call stack size exceeded
optionsAtMedia`

### CodeSandbox

https://codesandbox.io/s/embla-carousel-arrow-dots-react-forked-h4lgy6?file=/src/js/index.tsx

### Steps to reproduce

You should see the error on codesandbox 

### Expected behavior

- It should just show the carousel

**Comment by davidjerleke** [comment] 2023-07-07 21:21
Hi @hamidrezahanafi,

Thank you for your complete bug report. I can confirm that this is a bug. I will create a fix for this and let you know when I've done so.

Best,
David

**Comment by davidjerleke** [comment] 2023-07-08 09:36
To be released with **v8.0.0-rc09**.

**Comment by davidjerleke** [comment] 2023-07-08 19:48
@hamidrezahanafi I've released a bug fix with [v8.0.0.-rc09](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc09). Give it a try and let me know if it's working as intended now.

**Closed** 2023-07-08 19:49 UTC
Labels: bug, resolved

**Comment by hamidrezahanafi** [comment] 2023-07-08 21:24
Confirmed, it's fixed and working as expected with [v8.0.0-rc09](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc09).
