### ISSUE TITLE
Feature Request: Preload Next and Previous Slides in Loop Mode

### ISSUE THREAD

**Issue by 0xtlt** [davidjerleke/embla-carousel#585] opened 2023-09-28 09:37 UTC
### Is your feature request related to an issue?

- While using Embla Carousel with the loop feature enabled, I am facing an issue where as I slide through slides 1, 2, 3, 4, 5, it works fine, but when it loops back, slide 1 only appears when it's in the container. The expected behavior is for slide 1 to be preloaded into position before it comes into view, ensuring a seamless transition as the slides loop around. A detailed example illustrating this issue can be found [here](https://github.com/0xtlt/issues/tree/main/embla-preload).

### Describe the solution you'd like

- I propose an option be added to the Embla Carousel settings that allows for preloading a specified number of slides ahead and behind the current slide while in loop mode, to ensure a smooth transition as the slides loop around. Example:

```javascript
const embla = EmblaCarousel(emblaNode, {
  loop: true,
  preloadSlides: 2,
  // other options...
});
```

In this setup, `preloadSlides: 2` would mean that two slides ahead and two slides behind the current slide are preloaded into position, ensuring a smooth transition as the slides loop around.

### Additional context

- The issue arises when looping from slide 5 to slide 1, where slide 1 isn't preloaded into position, causing it to only appear once it's in the container. A seamless transition is expected as it loops back to slide 1.

I have been using Embla Carousel extensively and it's by far the best carousel library I have come across. The flexibility and performance it offers are unparalleled. However, having the ability to preload slides in a loop would enhance the user experience significantly, especially in scenarios similar to the one I am facing. Thank you for considering this feature request.

**Comment by davidjerleke** [comment] 2023-09-28 11:15
Hi @0xtlt,

Thank you for your question. As stated in the contribution guidelines, please create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/categories/q-a) before jumping into issues. You can copy paste the issue description to the discussion.

I don't think it's clear what you want to achieve when checking your [repository](https://github.com/0xtlt/issues/tree/main/embla-preload) out so please create a CodeSandbox that clearly demonstrates what you want to achieve or link to a carousel that already does this.

Thank you for understanding.

Best,
David

**Comment by davidjerleke** [comment] 2023-10-02 09:29
@0xtlt let me know if you're interested in pursuing this when you've [read my response](https://github.com/davidjerleke/embla-carousel/issues/585#issuecomment-1738950465).

**Comment by davidjerleke** [comment] 2023-10-04 06:34
@0xtlt I will delete this issue soon if you don’t respond.

**Comment by davidjerleke** [comment] 2023-10-05 08:07
Thanks for the additional details @sarussss.

I think I have a pretty good picture of what you and @0xtlt are doing wrong now. Embla doesn't hide slides and load them as you scroll. Your problem is caused by a **faulty markup and CSS setup**. You're setting `overflow: hidden;` on a container of your own choice and therefore you don't even have a proper bare minimum setup. There's no surprise in why stuff isn't working as intended.

The [docs make it very clear](https://www.embla-carousel.com/get-started/module/) that the **bare minimum setup** has to be:

> A minimal setup requires an **overflow wrapper** and a **scroll container**. Start by adding the following **HTML** structure to your carousel:

```HTML
<div class="embla">
  <div class="embla__container">
    <div class="embla__slide">Slide 1</div>
    <div class="embla__slide">Slide 2</div>
    <div class="embla__slide">Slide 3</div>
  </div>
</div>
```

> The wrapping element with the classname `embla` is needed to cover the scroll overflow. The element with the `container` classname is the scroll body that scrolls the slides. Continue by adding the following **CSS** to these elements:

```css
.embla {
  overflow: hidden;
}
.embla__container {
  display: flex;
}
.embla__slide {
  flex: 0 0 100%;
  min-width: 0;
}
```

🚨 Now. If you want **the previous and next slide to be visible**, don't move `overflow: hidden;` to another container of your own choice (breaking the required setup). Just set slide sizes to something less than `100%`. For example, `80%` and you're good to go:

```diff
.embla__slide {
- flex: 0 0 100%; // Remove this
+ flex: 0 0 80%; // Add this
  min-width: 0;
}
```

@sarussss here's [your sandbox](https://codesandbox.io/s/embla-carousel-loop-vanilla-forked-kh8dpc?file=/src/css/embla.css) but I've corrected your faulty markup so it's working as intended now.

Best,
David

**Comment by sarussss** [comment] 2023-10-09 02:33
Hi @davidjerleke ,
Thank you very much for this great answer, and I'm really sorry I had some events recently and couldn't respond to you as soon as possible.

**Comment by davidjerleke** [comment] 2023-10-09 04:34
@sarussss thank you for getting back to me. It seems like my explanation and sandbox demonstration solved your problem? 

If yes, I’m going to close this issue, because @0xtlt isn’t responding at all.

Best,
David

**Comment by sarussss** [comment] 2023-10-09 06:27
Yes, my problem is solved. @davidjerleke thank you.

**Closed** 2023-10-09 06:30 UTC
Labels: demonstration
