### ISSUE TITLE
[Bug]: {loop:true} option does not work when there're only two slides

### ISSUE THREAD

**Issue by Kimi-Gao** [davidjerleke/embla-carousel#1000] opened 2024-09-12 09:54 UTC
### Which variants of Embla Carousel are you using?

- [X] embla-carousel **(Core)**
- [X] embla-carousel-react
- [ ] embla-carousel-vue
- [ ] embla-carousel-svelte
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-scroll
- [ ] embla-carousel-solid
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-fade
- [ ] embla-carousel-docs **(Documentation)**
- [ ] embla-carousel-docs **(Generator)**

### Steps to reproduce

{loop:true} option does not work when there only two slides
3 slides looks good

### Expected Behavior

It can be switched in a loop

### Additional Context

I have also tried...

### CodeSandbox

https://codesandbox.io/p/sandbox/embla-carousel-loop-react-forked-j9jwym

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues
- [X] I agree to follow this project's Contributing Guidelines for bug reports

**Comment by davidjerleke** [comment] 2024-09-12 10:19
@Kimi-Gao a friendly reminder: Please make an effort and do some research because it's tedious answering the same questions again and again.

This is what the docs say about the [loop option](https://www.embla-carousel.com/api/options/#loop):

> Embla automatically falls back to `false` if slide content isn't enough to create the loop effect without visible glitches.

- Duplicate of: https://github.com/davidjerleke/embla-carousel/issues/124#issuecomment-731561708

**Closed by davidjerleke** 2024-09-12 10:19 UTC
Labels: bug
