### ISSUE TITLE
Prev/Next button documentation for Vue

### ISSUE THREAD

**Issue by Thinkro** [davidjerleke/embla-carousel#445] opened 2023-03-22 14:45 UTC
### Feature request is related to

- [x] embla-carousel-vue
- [x] embla-carousel-docs (documentation website)

### Describe the solution you'd like

Example with all features of Embla
- Prev/Next buttons
- Dots

E.g. the `const dots = computed(() => emblaApi.value?.scrollSnapList() || []);` for dots, what's the similar for prev/next buttons?

Thanks for your great work!

**Comment by davidjerleke** [comment] 2023-03-22 20:12
Hi @Thinkro,

Thank you for your feature request. I've had a similar question about achieving **prev/next** and **dot** navigation with `embla-carousel-vue` before. Check this CodeSandbox in [this comment](https://github.com/davidjerleke/embla-carousel/issues/383#issuecomment-1278993224) out and see if that's the example you're looking for?

---

About the [examples page](https://www.embla-carousel.com/examples/static/) missing Vue examples - I have that on my to do list for this project. But I'm the sole developer on this project and a huge to do so things are progressing slowly. I can't give you an ETA on when they will be available. Until then, you can browse the documentation website API reference together with the react examples. It might help you on the right track and see how things are solved there.

Best,
David

**Comment by davidjerleke** [comment] 2023-03-31 04:00
@Thinkro did you check the [CodeSandbox](https://codesandbox.io/s/adoring-dream-8yqk7r) out?

**Comment by Thinkro** [comment] 2023-03-31 11:31
@davidjerleke yes, i just forgot to comment. Thank you!

**Comment by davidjerleke** [comment] 2023-04-03 09:21
Duplicate of #383.

**Closed by davidjerleke** 2023-04-03 09:21 UTC
Labels: feature request, vue

**Comment by gilesbutler** [comment] 2023-04-24 09:35
Thanks for the example @davidjerleke 👍 super handy!

**Comment by davidjerleke** [comment] 2023-04-24 09:57
I'm glad it helped @gilesbutler. One day I'm hoping to get time to setup **Vue** examples on the [examples page](https://www.embla-carousel.com/examples/static/).

Cheers,
David
