### ISSUE TITLE
[Feat]: Continuously running carousel (ticker, marquee, ..)

### ISSUE THREAD

**Issue by openscript** [davidjerleke/embla-carousel#114] opened 2020-10-31 16:53 UTC
Hello everybody

I'm using Embla already in a project and it's great. Thank you for the amazing work!

Now I have the use case to build a carousel which runs continuously like a "stock market" ticker. So no speed up and slow down. Do you think it's easy to build something like that with Embla? Where would be a good starting point?

**Comment by davidcetinkaya** [comment] 2020-10-31 17:00
Hello Robin (@openscript),

Thank you for your question.
Is [this CodeSandbox](https://github.com/davidcetinkaya/embla-carousel/issues/105#issuecomment-695769772) what you’re looking for?

Let me know if I understod you correctly and it did help.

Best,
David

**Comment by openscript** [comment] 2020-10-31 17:46
Hello David (@davidcetinkaya)

Thank you for the very quick response.

The CodeSandbox shows exactly what I want, except that it doesn't start running after it has been dragged, but I think it's not to hard to implement this for the `settle` hook? :)

**Comment by davidcetinkaya** [comment] 2020-10-31 18:39
Hi again Robin (@openscript),

Yes I think the `settle` hook is appropriate for what you want to achieve. So something along those lines:

```ts
embla.on('settle', () => {
  /*
    Run the same code that scrolls the carousel slowly.
    You probably want to extract it into a reusable function
  */
})
```

Please let me know if you have other requirements or questions.

Kindly,
David

**Comment by openscript** [comment] 2020-10-31 22:01
Thank you for taking the time and helping me out.

I've tried to implement it for a while, but I get very strange side-effects. I thought a video of the screen would be the easiest to show it:

https://drive.google.com/file/d/1rBKMEgZJFVjHT49NW9YL5_2PpxtwU3BJ/view

My code looks like this:

```
import styled from '@emotion/styled';
import { useEmblaCarousel } from 'embla-carousel/react';
import { EmblaCarousel } from 'embla-carousel/vanilla';
import { Engine } from 'embla-carousel/vanilla/components/engine';
import React, { useEffect } from 'react';

const Viewport = styled.section`
  overflow: hidden;
`;

const Container = styled.div`
  display: flex;
`;

const Slide = styled.div`
  position: relative;
  min-width: 100%;
`;

export type TickerProps = {};

export function Ticker() {
  const [tickerRef, ticker] = useEmblaCarousel({ loop: true, dragFree: true, containScroll: 'trimSnaps' });

  const startScrolling = (engine: Engine, ticker: EmblaCarousel) => {
    engine.scrollBody.useSpeed(0.01);
    engine.scrollTo.index((ticker.scrollSnapList().length || 0) - 1, -10);
  };

  useEffect(() => {
    const engine = ticker?.dangerouslyGetEngine();

    if (engine && ticker) {
      ticker?.on('settle', () => startScrolling(engine, ticker));

      startScrolling(engine, ticker);
    }
  }, [ticker]);

  return (
    <Viewport ref={tickerRef}>
      <Container>
        <Slide>111111111111</Slide>
        <Slide>222222222222</Slide>
        <Slide>333333333333</Slide>
      </Container>
    </Viewport>
  );
}
```
Would it help you if I set up a CodesandBox? Do you have a Embla TypeScript React sandbox I could use?

**Comment by davidcetinkaya** [comment] 2020-11-01 10:39
Hello Robin (@openscript),

Thank you for the additional information. Seems like I might have misunderstood your requirements.

> It seems like the original has the same problem without my modifications. If you wait until it comes to the end, it is also getting slower and slower.

This is intentional. The requirements mentioned in issue #105 was to show users that the content is scrollable. So the idea was to start scrolling from the beginning and stop scrolling at the end of the content. The easing at the beginning and the end was not an issue there.

So let's go through **your use case** and requirements. Is this what you're looking for:

- The content should scroll automatically without any easing whatsoever as long as the carousel isn't dragged.
- It should scroll and loop endlessly.
- It should stop when the user drags the carousel and start over when the carousel has settled

?

Kindly,
David

**Comment by openscript** [comment] 2020-11-01 10:56
Hello David (@davidcetinkaya)

It made me happy to see your kind reply. Thank you!

Yes, I think we are talking about the same use cases. Easing is not required, but it would maybe be nice for the speed up at the beginning and after dragging. Easing at the end doesn't make sense to me, if it's an endless loop.

I want to achieve something like on the https://www.gatsbyjs.com/ website, but with dragging:
![image](https://user-images.githubusercontent.com/1105080/97800886-166eb600-1c39-11eb-8273-68ecba07a107.png)

Have a great day,

Robin

**Comment by davidcetinkaya** [comment] 2020-11-01 11:00
Hi Robin (@openscript),

Thanks for the example link. That helps 🙂. I'll see if I can create a CodeSandbox for you. I'll let you know how it goes when I've had the chance to do so.

Best,
David

**Comment by davidcetinkaya** [comment] 2020-11-02 10:33
Hello again Robin (@openscript),

I've created a [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-114-3jf38?file=/src/js/EmblaCarousel.js:1275-1289) for you. This sandbox basically re-creates the internal Embla animation loop without the easing.

Please let me know if it meets your requirements.

Kindly,
David

**Comment by openscript** [comment] 2020-11-02 12:02
Hi David (@davidcetinkaya)

Thank you so much! This is exactly what I wanted to achieve :)

Have a great day

Robin

**Comment by davidcetinkaya** [comment] 2020-11-02 12:12
Hi Robin (@openscript),

Just realized that you should probably stop the auto scrolling and start it again by hooking on to the Embla `resize` hook.

```ts
embla.on('resize', () => {
  stopAutoScroll();
  startAutoScroll();
});
```

I will update the CodeSandbox when I get the chance, but feel free to implement it yourself until then.

Have a nice week!
David

**Comment by filiptvarek** [comment] 2021-09-15 14:59
Hello, this solution isn't working since version 4.4.0. Loop does not working properly. Is here any solution for 4.5.3 please? To reproduce it you can only swap version in your CodeSandobox or [my modified](https://codesandbox.io/s/embla-carousel-react-github-issue-114-forked-5r4hp?file=/src/js/EmblaCarousel.js) version with 4.5.3 and faster scroll.

**Comment by davidcetinkaya** [comment] 2021-09-15 19:11
Hi @filiptvarek,

Thanks for noticing this. It stopped working because I refactored some internal methods in later versions. I've updated the original [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-114-3jf38?file=/src/js/EmblaCarousel.js:1275-1289) in [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/114#issuecomment-720385830) and it should work as expected now.

Cheers,
David

**Comment by filiptvarek** [comment] 2021-09-16 07:51
I works. Thank you very much

**Comment by Github010101011** [comment] 2022-05-23 18:04
How can i make the carousel have 3 images per page. Rather than one big one?

**Comment by Github010101011** [comment] 2022-05-23 19:16
@davidjerleke thanks! Ran into another issue though... When i set the slide size to 10%, slidesToScroll: 5, there's a huge gap on the left side, and slides start to disappear.  How do i fix this issue?

**Comment by davidjerleke** [comment] 2022-05-23 19:51
@Github010101011 I have no idea what your setup looks like so I don't know why you have a huge gap.

**Comment by samdhoffman** [comment] 2022-06-02 14:48
hey @davidjerleke thank you for creating this example! is there a way to control the speed of the carousel when implementing it like this?

**Comment by ameliagroen** [comment] 2022-06-15 10:12
Curious on how to do this with Vanilla JS?

**Comment by easydrops** [comment] 2022-06-17 08:43
@ameliagroen @samdhoffman As for VanillaJS, I am fiddling around with this myself. And this seems to be working for me.
But tbh I am not very familiar with the requestAnimationFrame API. So I don't know if this might lead to any drawbacks.

```javascript

let rafId = 0;

const animate = () => {
  if(!embla) return
  const engine = embla.dangerouslyGetEngine();
  engine.location.add(-0.025); // controls the speed
  engine.target.set(engine.location);
  engine.scrollLooper.loop(-1);
  engine.slideLooper.loop();
  engine.translate.to(engine.location);
  rafId = requestAnimationFrame(animate)
}
const startAutoScroll = () => {
 rafId = requestAnimationFrame(animate)
}
const stopAutoScroll = () => {
  rafId = cancelAnimationFrame(rafId) || 0;
}
embla.on("settle", startAutoScroll);
embla.on("pointerDown", stopAutoScroll);
startAutoScroll();    
```

Hope this helps :)

**Comment by ruie** [comment] 2023-03-16 03:36
Hey guys,

Thank you very much for sharing the snippets of ticker functionality.

I'm currently using it with variable width but for some reason it doesn't loop back when its on ticker mode. 

If I'm using drag, looping is working as intended.

I think I'm missing something with internalEngine method. I tried looking in docs but can't find any reference for this.

Here is a [CodeSandbox](https://codesandbox.io/s/embla-carousel-variable-widths-react-not-looping-jfstre?file=/src/js/EmblaCarousel.jsx:460-474) for your reference.

Thank you so much guys!

**Comment by abdulrauf11** [comment] 2023-04-10 11:49
Hey everyone 👋  Super cool example! Can anyone tell me how to control the speed of the ticker animation?

**Comment by dan-wu-open** [comment] 2023-04-28 22:55
@abdulrauf11 just change the number here
```
    engine.location.add(-1);
    engine.scrollLooper.loop(-1);
```

I'm using 0.3 which is a slower speed

**Comment by pedrobernardina** [comment] 2023-08-02 18:35
> Hey guys,
> 
> Thank you very much for sharing the snippets of ticker functionality.
> 
> I'm currently using it with variable width but for some reason it doesn't loop back when its on ticker mode.
> 
> If I'm using drag, looping is working as intended.
> 
> I think I'm missing something with internalEngine method. I tried looking in docs but can't find any reference for this.
> 
> Here is a [CodeSandbox](https://codesandbox.io/s/embla-carousel-variable-widths-react-not-looping-jfstre?file=/src/js/EmblaCarousel.jsx:460-474) for your reference.
> 
> Thank you so much guys!

Same here :(

**Comment by dash-james** [comment] 2023-09-07 14:14
> @ameliagroen @samdhoffman As for VanillaJS, I am fiddling around with this myself. Adapting the sandbox above, this seems to be working for me. But tbh I am not very familiar with the requestAnimationFrame API. So I don't know if this might lead to any drawbacks.
> 
> ```js
> let rafId = 0;
> 
> const animate = () => {
>   const engine = embla.dangerouslyGetEngine();
>   engine.location.add(-0.025); // controls the speed
>   engine.target.set(engine.location);
>   engine.scrollLooper.loop(-1);
>   engine.slideLooper.loop();
>   engine.translate.to(engine.location);
>   rafId = requestAnimationFrame(animate)
> }
> const startAutoScroll = () => {
>  rafId = requestAnimationFrame(animate)
> }
> const stopAutoScroll = () => {
>   rafId = cancelAnimationFrame(rafId) || 0;
> }
> embla.on("settle", startAutoScroll);
> embla.on("pointerDown", stopAutoScroll);
> startAutoScroll();    
> ```
> 
> Hope this helps :)

Unfortunately this doesn't work from v8 onwards :/

**Comment by 7iomka** [comment] 2023-10-02 22:06
It is a pity that there is no official example that would be supported when the next update version is released.

**Comment by davidjerleke** [comment] 2023-10-03 07:17
Hi @7iomka,

I don't doubt that you mean well, but I don't think it's helping. I'm the sole maintainer of this project and always have an insane backlog. [This is what's been done](https://github.com/davidjerleke/embla-carousel/issues/321#roadmap) for the upcoming v8.

If devs really want me to add more features/plugins, and if I'm to spend **even more** of my unpaid spare time than I already do, I have to be motivated by something. I want this comment to be constructive so here are ways to not just say I want this an that, but also actually support this project:

- ⭐ Star it if you already haven't, and you find yourself using it in multiple projects and you're overall satisfied with it.
- 📣 Share it in social media like Reddit or similar.
- 💰 Donate to this project.

More support means better chances for me to add more examples, more features and plugins.

Best,
David

**Comment by AmeerSapadmi** [comment] 2023-10-10 14:09
Hello,

For this sandbox that was shared earlier by @davidjerleke: 
https://codesandbox.io/s/embla-carousel-react-github-issue-114-3jf38?file=/src/js/EmblaCarousel.js:1275-1289

I have noticed a bug where when you right click on the carousel slides the carousel starts to move faster, as you keep right clicking it goes on faster and faster.

What could be causing this?

**Comment by Poylar** [comment] 2023-10-25 11:14
in version  "embla-carousel-react": "^8.0.0-rc14", this example not work anymore

**Comment by Poylar** [comment] 2023-10-25 11:16
[https://codesandbox.io/s/embla-carousel-react-github-issue-114-forked-9wm39t?file=/package.json:198-237](i fork codesandbox with new version)

**Comment by davidjerleke** [comment] 2023-11-14 10:36
@Poylar there is a plugin being developed for this purpose which will be named `embla-carousel-auto-scroll` which is 80% complete at the time of writing.

**Comment by davidjerleke** [comment] 2024-01-12 14:01
Hi @Poylar, @dash-james, @AmeerSapadmi, @7iomka, @pedrobernardina, @abdulrauf11, @ameliagroen, @ruie, @samdhoffman,

I'm very close to wrapping up this plugin. If anyone would like to help out and test it out before the release, I would very much appreciate that. Maybe we can catch one or two bugs before the release. 

If you're interested, I'm going to create CodeSandboxes that I will share with you here so let me know what setup you prefer:

- Vanilla
- Vanilla + TypeScript
- React
- React + Typescript
- etc.

Thanks in advance!

**Comment by mdrahiem** [comment] 2024-01-12 14:13
Hey @davidjerleke I would prefer React + Typescript. Also may I know what test scenarios you want me to cover? I have never done this before 😅  but I would love to do it 😬 . Please guide me. TIA.

**Comment by Poylar** [comment] 2024-01-12 23:23
hi, i would prefer react + js

**Comment by davidjerleke** [comment] 2024-01-13 20:44
@Poylar and @mdrahiem thank you for considering testing this plugin. **CodeSandboxes** here:

### React + JavaScript
- [Code view](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-sdh7j8)
- [App view](https://sdh7j8.csb.app/)

### React + TypeScript
- [Code view](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-krfhmt)
- [App view](https://krfhmt.csb.app/)

> Also may I know what test scenarios you want me to cover? 

Please feel free to test it anyway you want. For example, you can read what the different options do below and test and see if they behave as expected. I will temporarily just dump the documentation page for the `AutoScroll` plugin below:

---

# Documentation

## Options

Below follows an exhaustive **list of all** `Auto Scroll` **options** and their default values.

### speed

Type: <BrandPrimaryText>`number`</BrandPrimaryText>  
Default: <BrandSecondaryText>`2`</BrandSecondaryText>

Number of pixels auto scroll should advance per frame.

---

### startDelay

Type: <BrandPrimaryText>`number`</BrandPrimaryText>  
Default: <BrandSecondaryText>`1000`</BrandSecondaryText>

Number of milliseconds auto scroll should **wait before it starts**. This also applies when user interactions end and [stopOnInteraction](/plugins/auto-scroll/#stoponinteraction) is `false`.

---

### direction

Type: <BrandPrimaryText>`string`</BrandPrimaryText>  
Default: <BrandSecondaryText>`forward`</BrandSecondaryText>

This option is used to set the auto scroll direction. Set it to `backward` if you want it to scroll in the opposite direction.

---

### playOnInit

Type: <BrandPrimaryText>`boolean`</BrandPrimaryText>  
Default: <BrandSecondaryText>`true`</BrandSecondaryText>

If set to `false`, you'll have to start auto scroll yourself by calling the [play](/plugins/auto-scroll/#play) method.

---

### stopOnInteraction

Type: <BrandPrimaryText>`boolean`</BrandPrimaryText>  
Default: <BrandSecondaryText>`true`</BrandSecondaryText>

If set to `false`, auto scroll will not be disabled after drag interactions, and it will restart every time after an interaction.

---

### stopOnMouseEnter

Type: <BrandPrimaryText>`boolean`</BrandPrimaryText>  
Default: <BrandSecondaryText>`false`</BrandSecondaryText>

When enabled, auto scroll will stop when a mouse pointer enters the Embla Carousel container. If [stopOnInteraction](/plugins/auto-scroll/#stoponinteraction) is also `false`, auto scroll will resume when the mouse leaves the carousel container.

---

### stopOnFocusIn

Type: <BrandPrimaryText>`boolean`</BrandPrimaryText>  
Default: <BrandSecondaryText>`true`</BrandSecondaryText>

When enabled, auto scroll will stop when a focusable element inside the carousel recieves focus. If [stopOnInteraction](/plugins/auto-scroll/#stoponinteraction) is `false`, auto scroll will resume when the user leaves focus.

---

### rootNode

Type: <BrandPrimaryText>`(emblaRoot: HTMLElement) => HTMLElement | null`</BrandPrimaryText>  
Default: <BrandSecondaryText>`null`</BrandSecondaryText>

The **node** that should **respond** to user **interactions** like [stopOnMouseEnter](/plugins/auto-scroll/#stoponmouseenter) and [stopOnInteraction](/plugins/auto-scroll/#stoponinteraction). If this is omitted, the node that wraps the Embla Carousel will be used as default.

---

## Methods

Below follows an exhaustive **list of all** `Auto Scroll` **methods** with their respective parameters and return values.

---

### play

Parameters: <BrandPrimaryText>`startDelayOverride?: number`</BrandPrimaryText>  
Returns: <BrandSecondaryText>`void`</BrandSecondaryText>

Start auto scroll. Pass a **startDelayOverride** if you want to change the [startDelay](/plugins/auto-scroll/#startdelay) option after the plugin has been initialized.

---

### stop

Parameters: <BrandPrimaryText>`none`</BrandPrimaryText>  
Returns: <BrandSecondaryText>`void`</BrandSecondaryText>

Stops auto scroll.

---

### reset

Parameters: <BrandPrimaryText>`none`</BrandPrimaryText>  
Returns: <BrandSecondaryText>`void`</BrandSecondaryText>

Stops auto scroll and starts over. This will only take effect if auto scroll is playing. If auto scroll is stopped, this method won't trigger anything.

---

### isPlaying

Parameters: <BrandPrimaryText>`none`</BrandPrimaryText>  
Returns: <BrandSecondaryText>`boolean`</BrandSecondaryText>

Returns a boolean whether the carousel is auto scrolling or not.

---

## Events

Below follows an exhaustive **list of all** `Auto Scroll` **events** together with information about how they work.

---

### autoScroll:play

Once: <BrandPrimaryText>`no`</BrandPrimaryText>

Fires when auto scroll starts playing.

---

### autoScroll:stop

Once: <BrandPrimaryText>`no`</BrandPrimaryText>

Fires when auto scroll stops scrolling.

---

**Comment by Poylar** [comment] 2024-01-14 02:57
@davidjerleke hi, should I create a new bug issue or reply to you here?

**Comment by davidjerleke** [comment] 2024-01-14 05:54
@Poylar since this isn’t released yet, you can reply to me in the PR here:

- #634 

Thanks!

**Comment by mdrahiem** [comment] 2024-01-14 11:12
Hello @davidjerleke I did test options and methods and below are the results.

**Options:**
✅ speed
✅ startDelay
✅ direction
✅ playOnInit
✅ stopOnInteraction
✅ stopOnMouseEnter
✅ stopOnFocusIn
❓ rootNode

**Methods:**
❌ play
✅ stop
❌ reset
❌ isPlaying

**Events:**
❓autoScroll:play
❓autoScroll:stop

✅ - Success  ❓- Not sure how to test    ❌ - Not working (I think)

For `isPlaying` I tried the below code.
```jsx
     <div>
        status:{' '}
        {emblaApi?.plugins().autoScroll?.isPlaying()
          ? 'playing'
          : 'not playing'}
      </div>
```

For `play`, `reset` I tried with below code.
```jsx
  const stopPlay = useCallback(
    (index) => {
      if (!emblaApi) return
      emblaApi.plugins().autoScroll?.stop()
      emblaApi.scrollTo(index)
    },
    [emblaApi]
  )

  const resumePlay = useCallback(
    (index) => {
      if (!emblaApi) return
      emblaApi.plugins().autoScroll?.play()
      emblaApi.scrollTo(index)
    },
    [emblaApi]
  )

  const resetPlay = useCallback(
    (index) => {
      if (!emblaApi) return
      emblaApi.plugins().autoScroll?.reset()
      emblaApi.scrollTo(index)
    },
    [emblaApi]
  )

      <button onClick={stopPlay}>Stop</button>
      <button onClick={resumePlay}>Resume</button>
      <button onClick={resetPlay}>Reset</button>
```

Please correct me if my above implementation is wrong for `play, reset, isPlaying` and I would be glad to test `Events` if I find some example. Thanks!

**Comment by davidjerleke** [comment] 2024-01-14 11:17
Thanks a lot for testing @mdrahiem!

I will update the CodeSandbox with the playing state, events and demonstrate how to do it. Stay tuned 👍.

**Comment by mdrahiem** [comment] 2024-01-14 12:44
Also an update on browsers.

✅ - Chromium Engine Version 120
✅ - Firefox 121.0
✅ - Safari Version 17.2.1

**Comment by davidjerleke** [comment] 2024-01-14 21:03
@mdrahiem please check the [CodeSandbox](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-krfhmt?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A143%2C1) again, I've added the features you weren't sure about so you can see how it's intended to work.

Best,
David

**Comment by mdrahiem** [comment] 2024-01-15 14:07
Thanks for updating the code @davidjerleke Below is the update on testing.

**Methods:**
✅ play
✅ stop
✅ isPlaying

**Events:**
✅ autoScroll:play
✅ autoScroll:stop

❌ reset - I was expecting the slider to be reset (start from slide 1) but what I see is, it stops for a while (because of `startDelay`) and then it plays from the same position. Please correct if my expectation is wrong.

❓ rootNode - I still couldn't find any implementation for this. I see the implementation in [javascript](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-sdh7j8) version though. 😄

**Comment by davidjerleke** [comment] 2024-01-16 12:34
@mdrahiem thank you for testing again 🙂!

> ❌ reset - I was expecting the slider to be reset (start from slide 1) but what I see is, it stops for a while (because of `startDelay`) and then it plays from the same position. Please correct if my expectation is wrong.

I think I need to update the description of what this does. That's valuable input, thanks 👍. The `reset` method does the following:

- If auto scroll is scrolling, it stops.
- When the carousel settles, the timer restarts using the `startDelay` option value.

It's useful when you're using previous/next buttons and want the carousel to continue after the user has navigated with the buttons and the carousel has settled. See [here](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-krfhmt?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A41%2C1-42%2C1) and [here](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-krfhmt?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A41%2C1-42%2C1).

---

❓ rootNode - I still couldn't find any implementation for this. I see the implementation in [javascript](https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-forked-sdh7j8) version though. 😄 

This allows you to select a custom element that should listen for `mouseenter` and `mouseleave`, if you don't want the default Embla root node (which is the element you attach `emblaRef` to). It's used when `stopOnMouseEnter` is `true`.

---

Did these explanations make sense? 

Best,
David

**Comment by mdrahiem** [comment] 2024-01-17 09:26
Thank you so much for taking time and explaining these. They makes sense now 🙂

**Comment by davidjerleke** [comment] 2024-01-17 09:31
@mdrahiem thanks for testing ⭐! The plugin will be released soon.

**Comment by davidjerleke** [comment] 2024-01-17 09:50
Thanks that's very kind of you @mdrahiem. @mdrahiem and anyone else reading this for that matter: 

If you want to **make contributions** you can browse **discussions** with the label [`help wanted`](https://github.com/davidjerleke/embla-carousel/discussions?discussions_q=is%3Aopen+label%3A%22help+wanted%22). We are happy to accept contributions from our users. For more details see the [contributing guidelines](https://github.com/davidjerleke/embla-carousel/blob/6cc0625490f72ca5180853de60b4eca531afd0f4/CONTRIBUTING.md).

After your pull request have been merged, you will automatically be added as a contributor [here](https://github.com/davidjerleke/embla-carousel?tab=readme-ov-file#contributors) and [here](https://github.com/davidjerleke/embla-carousel/graphs/contributors).

Best,
David

**Closed** 2024-01-26 09:12 UTC
Labels: feature request, plugin

**Comment by davidjerleke** [comment] 2024-01-26 09:42
- Sorry guys, was just about to publish this package but someone has taken a too similar name so I've asked them to unpublish their package before I can release the official package: https://github.com/nwidynski/embla-carousel-autoplay/issues/1.

**Comment by dcapinator** [comment] 2024-01-30 13:58
> Sorry guys, was just about to publish this package (`embla-carousel-auto-scroll`), but someone has taken a too similar name so I've asked them to unpublish their package before I can release the official package:
> 
> * [Package name confilct nwidynski/embla-carousel-autoplay#1](https://github.com/nwidynski/embla-carousel-autoplay/issues/1).
> 
> ## Update 2024-01-29
> The person in question unpublished their package but the NPM registry threw errors when I tried to publish `embla-carousel-auto-scroll`. I've contacted NPM support and they said that the package wasn't properly unpublished so they did that for me. Unfortunately, NPM say that I have to wait 24h before I can try publishing `embla-carousel-auto-scroll` again.

any updates or again you are waiting 24 hours ?

**Comment by davidjerleke** [comment] 2024-01-30 14:03
@dcapinator waiting additional 24 hours. Next publish attempt can be made in 6 hours.

**Comment by davidjerleke** [comment] 2024-01-31 08:15
## Update 2024-01-30
`embla-carousel-auto-scroll` has been released to the [NPM registry](https://www.npmjs.com/package/embla-carousel-auto-scroll).

### Update 2024-01-29
The person in question unpublished their package but the NPM registry threw errors when I tried to publish `embla-carousel-auto-scroll`. I've contacted NPM support and they said that the package wasn't properly unpublished so they did that for me. Unfortunately, NPM say that I have to wait 24h before I can try publishing `embla-carousel-auto-scroll` again.

### Update 2024-01-26
Sorry guys, was just about to publish this package (`embla-carousel-auto-scroll`), but someone has taken a too similar name so I've asked them to unpublish their package before I can release the official package: 

- https://github.com/nwidynski/embla-carousel-autoplay/issues/1.

**Comment by bayuzzs** [comment] 2025-02-06 19:08
good
