### ISSUE TITLE
Inconsistent animation speed depending on monitor refresh rate

### ISSUE THREAD

**Issue by macjuul** [davidjerleke/embla-carousel#387] opened 2022-10-22 23:38 UTC
### Bug is related to

- [x] embla-carousel (core package)

### Embla Carousel version

- v7.0.3

### Describe the bug

- The animation speed when navigating via controls or using `scrollTo` is affected by the refresh rate of your monitor. In my case, carousels will animate more than twice as fast on 144hz monitors compared to 60hz monitors, causing it to either feel to slow or too fast.

### CodeSandbox

- Not applicable, this can be tested by manually limiting the refresh rate of your browser on the Embla examples page.

### Steps to reproduce

1. View a carousel normally (either with 60Hz or higher)
2. Limit your browser framerate to 30Hz or lower (You can do this in Firefox by setting `layout.frame_rate` to 30 in `about:config`)
3. View the same carousel again, you will notice slide animations being twice as slow

### Expected behavior

- It is expected that the time it takes for the carousel to travel one snap point is not dependent on the monitors refresh rate as this can cause unintended side effects. I'm using Embla to create a slide animation between multiple forms in a stepper, and to some people the animation feels too slow, while for others it's fine.

### Additional context

- This issue is caused by `requestAnimationFrame` attempting to sync to the monitors refresh rate. This should be fixable by using the time value passed into the callback by `requestAnimationFrame` ([Here's an explanation on StackOverflow](https://stackoverflow.com/a/58628834))

Thank you for your great library!

**Comment by davidjerleke** [comment] 2022-10-23 07:59
Hi @macjuul,

Yep, I already have this on my to do so thank you for creating this issue 👍🏻. I’ll let you know when I have something.

Best,
David

**Comment by robksawyer** [comment] 2023-01-26 18:41
Anyway we could add the ability to adjust the ease type? Using different easings with the autoplay plugin would be a win!

**Comment by macjuul** [comment] 2023-03-26 10:54
Hey @davidjerleke, have you had any time to look into this yet? or perhaps an estimate on when this could be tackled?

Thanks!

**Comment by davidjerleke** [comment] 2023-03-26 17:19
Hi @macjuul,

Thanks for the follow up. I can’t give proper time estimates because I’m the sole dev on this project with a huge to do list, and I’m maintaining this on my spare time which means a little bit here and there.

But what I can say is that I have it planned for the `7.2.1` release:

- `7.2.0` (to be released soon, currently working on this)
- `7.2.1` *<— I have planned it for this release*

Best,
David

**Comment by macjuul** [comment] 2023-03-26 18:41
Great to hear @davidjerleke! Thanks for the heads up, looking forward to a fix. Take your time, no need to hurry 🙂

**Comment by davidjerleke** [comment] 2023-04-02 07:52
@macjuul, just wanted to let you know that I will start working on this issue the next time I work on this project. Can’t give an ETA though but I will start looking into it.

**Comment by macjuul** [comment] 2023-04-05 18:19
> Hi @macjuul,
> 
> If you want to help out and speed up the process, you could test [this CodeSandbox](https://s81z1o.csb.app/) on:
> 
> * On a 60 Hz device.
> * On a 120 Hz device.
> 
> The **total runtime** for the animation on each device **should be** something around `1500` milliseconds (give and take 30 milliseconds), no matter the refresh rate.
> 
> If that's the case, I have a good starting point and will continue implementing this feature into the Embla Carousel core. Also note that the runtime won't be exactly 1500 and may slightly vary from one try to another (about 30 milliseconds give and take).
> 
> Thanks in advance. David

This is indeed working perfectly on 144hz, 60hz, and 30hz. Good job!

**Comment by davidjerleke** [comment] 2023-04-05 19:25
@macjuul, thanks for taking time and testing it out 👍. I'll let you know when I have a working frame rate agnostic Embla draft.

**Comment by davidjerleke** [comment] 2023-04-22 06:21
Hi @macjuul and everyone tracking this issue. I’m done implementing this feature and it will be released with v8.0.0-rc01 pretty soon. I just have to update some examples on the documentation website. Stay tuned.

Best,
David

**Closed** 2023-04-22 18:54 UTC
Labels: bug, upcoming

**Comment by davidjerleke** [comment] 2023-04-22 18:55
To be released with v8.0.0-rc01.

**Comment by davidjerleke** [comment] 2023-04-26 05:27
@macjuul this feature has been released with [v8.0.0-rc01](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.0.0-rc01).

**Comment by bugproof** [comment] 2024-09-29 20:34
This library feels extremely slow for some reason on iOS 120 Hz still

**Comment by davidjerleke** [comment] 2024-09-30 06:49
> This library feels extremely slow for some reason on iOS 120 Hz still
> Transitions feel like 60hz

@bugproof it's hard to know what you mean with **extremely slow** because it's highly subjective, but the whole point with refresh rate agnostic animations, is that the animation duration should be the same regardless of monitor refresh rate. Otherwise the [duration option](https://www.embla-carousel.com/api/options/#duration) would be highly unpredictable:

- 60hz default speed
- 120hz twice as fast
- 240hz  four times as fast

Instead it should be (like it's designed now):

- 60hz default speed
- 120hz same speed as 60hz
- 240hz same speed as 60hz

You can easily test the speed with this code:

```tsx
let startTime = 0

emblaApi.on('settle', () => {
  const nowTime = new Date().getTime()
  const diffTime = nowTime - startTime

  console.log(`Transition took ${diffTime}ms`)
})

function scrollNextWithTimer() {
  startTime = new Date().getTime()
  emblaApi.scrollNext()
}

scrollNextWithTimer()
```

When you try that on monitors with different refresh rates, the animation should take approximately the same time, with an acceptable diff of 1-50 ms (because of how `requestAnimationFrame` works).

**Comment by bugproof** [comment] 2024-09-30 12:15
@davidjerleke the animation is not fluid on iOS browsers - it doesn't seem like 120hz. I compared it across few different libraries. 

https://blaze-slider.dev/ (has it's own issues but animations are very fluid)
https://github.com/beynar/svelte-light-carousel (also very fluid, probably the best one I've found in terms of animation smoothness)

If you use airbnb, they also have carousel component on mobile in reviews section, now compare embla-carousel to that on iOS and you will see what I mean.

**Comment by davidjerleke** [comment] 2024-09-30 13:54
@bugproof where did you test this? The [examples](https://www.embla-carousel.com/examples/predefined/) page in the documentation?

**Comment by bugproof** [comment] 2024-09-30 14:03
> @bugproof where did you test this? The [examples](https://www.embla-carousel.com/examples/predefined/) page? And what do you mean by **not fluid**? Does it stutter?

Not sure how to describe it. It's not stuttering. It's like using 60hz display instead of the 120hz one. I tested it on both examples page and my own project.

**Comment by davidjerleke** [comment] 2024-09-30 14:46
@bugproof please help me understand you better by being more precise with your words. Example:

Smooth or fluid animations: In my world, this means that the animation is continuous/fluid from point A to B, and doesn’t stutter/without choppiness, regardless of speed or how long it takes.

So based on that definition, it stuttering? Or is the animation still smooth/fluid, but you think it feels like the animation is taking too long on a 120hz screen?

**Comment by bugproof** [comment] 2024-09-30 22:37
> @bugproof please help me understand you better by being more precise with your words. Example:
> 
> Smooth or fluid animations: In my world, this means that the animation is continuous/fluid from point A to B, doesn’t stutter and isn’t choppy, regardless of the animation speed. Be it a slow or fast animation.
> 
> So based on that definition, is it stuttering? Or is the animation still smooth/fluid, but you think it feels like the animation is taking too long on a 120hz screen?

Then by your definition it's choppy/stuttering. It't not about animation speed but the way it runs on 120hz.

**Comment by davidjerleke** [comment] 2024-10-01 04:00
@bugproof could you provide a screen recording?

**Comment by bugproof** [comment] 2024-10-02 15:10
I use iPhone 13 pro. On the screen recording it's not visible as the recording has a fixed frame rate. I would need to record the physical screen with some other phone perhaps.

Yes I tested in the examples page you've linked.

**Comment by davidjerleke** [comment] 2024-10-03 19:52
@bugproof would you mind testing [this sandbox](https://vxjcsm.csb.app/) on both `120hz` and `60hz` and let me know if you experience the same problem in that sandbox?

**Comment by bugproof** [comment] 2024-10-06 12:14
> @bugproof would you mind testing [this sandbox](https://vxjcsm.csb.app/) on both `120hz` and `60hz` and let me know if you experience the same problem in that sandbox?

Yes the same problem in that sandbox. The animation looks like it's skipping some frames.

**Comment by davidjerleke** [comment] 2024-10-06 12:17
@bugproof thanks. I’ll look into it when I get the chance. It’s a bug in that case.

**Comment by bugproof** [comment] 2024-10-06 12:21
Also both blaze slider and the other slider I have tried don't have this issue. The sliding animation there is buttery smooth almost like it was a native iOS app.

**Comment by davidjerleke** [comment] 2024-10-06 12:25
@bugproof I know what the problem is. I don’t have access to 120hz screens so that’s why I couldn’t test this. But you’ve helped me narrow down the bug.

**Comment by davidjerleke** [comment] 2024-10-23 10:43
@bugproof would you mind helping out one more time and try this [CodeSandbox](https://ntyl6q.csb.app/) to see if the animation is smooth on your 120hz devices?

**Comment by bugproof** [comment] 2024-10-23 12:07
> @bugproof would you mind helping out one more time and try this [CodeSandbox](https://ntyl6q.csb.app/) to see if the animation is smooth on your 120hz devices?

Just tried it. Works slightly better I think? Still not as silky smooth as other libs from my list.

**Comment by davidjerleke** [comment] 2024-10-23 12:44
@macjuul would you mind testing the [CodeSandbox](https://ntyl6q.csb.app/) on your `144hz` monitor and see if the animation is smooth?
